// Extended German noun bank — batch 2 of the curated expansion (~690 → ~2000).
// Common A2-level nouns, each with a hand-checked article and Turkish meaning.
import type { CuratedWord } from '@/lib/mock-data';

const n = (word: string, article: string, tr: string, en: string): CuratedWord => ({
  id: word,
  word,
  language: 'de',
  type: 'noun',
  article,
  shortDef: { tr, en },
});

export const GERMAN_NOUNS_EXTRA: CuratedWord[] = [
  // ── People & roles ──────────────────────────────────────────────────────────
  n('Bürger', 'der', 'vatandaş', 'citizen'),
  n('Künstler', 'der', 'sanatçı', 'artist'),
  n('Sänger', 'der', 'şarkıcı', 'singer'),
  n('Schauspieler', 'der', 'oyuncu, aktör', 'actor'),
  n('Politiker', 'der', 'siyasetçi', 'politician'),
  n('Soldat', 'der', 'asker', 'soldier'),
  n('Richter', 'der', 'hâkim, yargıç', 'judge'),
  n('Anwalt', 'der', 'avukat', 'lawyer'),
  n('Ingenieur', 'der', 'mühendis', 'engineer'),
  n('Pilot', 'der', 'pilot', 'pilot'),
  n('Koch', 'der', 'aşçı', 'cook'),
  n('Bäcker', 'der', 'fırıncı', 'baker'),
  n('Friseur', 'der', 'kuaför, berber', 'hairdresser'),
  n('Bauer', 'der', 'çiftçi', 'farmer'),
  n('Krankenschwester', 'die', 'hemşire', 'nurse'),
  n('Polizist', 'der', 'polis memuru', 'police officer'),

  // ── Body ────────────────────────────────────────────────────────────────────
  n('Lippe', 'die', 'dudak', 'lip'),
  n('Brust', 'die', 'göğüs', 'chest'),

  // ── Food & kitchen ──────────────────────────────────────────────────────────
  n('Soße', 'die', 'sos', 'sauce'),
  n('Pilz', 'der', 'mantar', 'mushroom'),
  n('Erdbeere', 'die', 'çilek', 'strawberry'),
  n('Gewürz', 'das', 'baharat', 'spice'),
  n('Pfeffer', 'der', 'biber (baharat)', 'pepper'),

  // ── Home & objects ──────────────────────────────────────────────────────────
  n('Schublade', 'die', 'çekmece', 'drawer'),
  n('Wecker', 'der', 'çalar saat', 'alarm clock'),
  n('Eimer', 'der', 'kova', 'bucket'),
  n('Kamm', 'der', 'tarak', 'comb'),
  n('Mülleimer', 'der', 'çöp kovası', 'bin'),
  n('Waschmaschine', 'die', 'çamaşır makinesi', 'washing machine'),
  n('Ofen', 'der', 'fırın, soba', 'oven, stove'),
  n('Schüssel', 'die', 'kâse', 'bowl'),

  // ── Clothing ────────────────────────────────────────────────────────────────
  n('Gürtel', 'der', 'kemer', 'belt'),
  n('Krawatte', 'die', 'kravat', 'tie'),
  n('Knopf', 'der', 'düğme', 'button'),

  // ── Nature & weather ────────────────────────────────────────────────────────
  n('Wiese', 'die', 'çayır', 'meadow'),
  n('Feld', 'das', 'tarla, alan', 'field'),
  n('Sturm', 'der', 'fırtına', 'storm'),
  n('Blitz', 'der', 'şimşek', 'lightning'),
  n('Nebel', 'der', 'sis', 'fog'),

  // ── City & buildings ────────────────────────────────────────────────────────
  n('Turm', 'der', 'kule', 'tower'),
  n('Schloss', 'das', 'şato, kilit', 'castle, lock'),
  n('Rathaus', 'das', 'belediye binası', 'town hall'),
  n('Zaun', 'der', 'çit', 'fence'),
  n('Tor', 'das', 'kapı (büyük), gol', 'gate, goal'),

  // ── Abstract concepts ───────────────────────────────────────────────────────
  n('Lüge', 'die', 'yalan', 'lie'),
  n('Sinn', 'der', 'anlam, mantık', 'sense, meaning'),
  n('Erinnerung', 'die', 'anı, hatıra', 'memory'),
  n('Macht', 'die', 'güç, iktidar', 'power'),

  // ── Technology & media ──────────────────────────────────────────────────────
  n('Bildschirm', 'der', 'ekran', 'screen'),
  n('Tastatur', 'die', 'klavye', 'keyboard'),
  n('Drucker', 'der', 'yazıcı', 'printer'),
  n('Akku', 'der', 'şarjlı pil, batarya', 'battery'),
  n('Ladegerät', 'das', 'şarj aleti', 'charger'),
  n('Lautsprecher', 'der', 'hoparlör', 'speaker'),
  n('Kopfhörer', 'der', 'kulaklık', 'headphones'),
  n('Kamera', 'die', 'kamera', 'camera'),
  n('Datei', 'die', 'dosya', 'file'),
  n('Sender', 'der', 'kanal, verici', 'channel, transmitter'),
  n('Werbung', 'die', 'reklam', 'advertisement'),
  n('Anwendung', 'die', 'uygulama', 'application'),
  n('Verbindung', 'die', 'bağlantı', 'connection'),

  // ── Work & office ───────────────────────────────────────────────────────────
  n('Stelle', 'die', 'iş, pozisyon; yer', 'job, position'),
  n('Vertrag', 'der', 'sözleşme', 'contract'),
  n('Gehalt', 'das', 'maaş', 'salary'),
  n('Lohn', 'der', 'ücret', 'wage'),
  n('Besprechung', 'die', 'toplantı', 'meeting'),
  n('Termin', 'der', 'randevu', 'appointment'),
  n('Projekt', 'das', 'proje', 'project'),
  n('Abteilung', 'die', 'departman, bölüm', 'department'),
  n('Pause', 'die', 'mola, ara', 'break'),
  n('Urlaub', 'der', 'tatil, izin', 'holiday, leave'),
  n('Bewerbung', 'die', 'iş başvurusu', 'application (job)'),
  n('Lebenslauf', 'der', 'özgeçmiş', 'CV, résumé'),

  // ── School & education ──────────────────────────────────────────────────────
  n('Unterricht', 'der', 'ders', 'lesson, class'),
  n('Klasse', 'die', 'sınıf', 'class'),
  n('Note', 'die', 'not (okul)', 'grade'),
  n('Hausaufgabe', 'die', 'ev ödevi', 'homework'),
  n('Wörterbuch', 'das', 'sözlük', 'dictionary'),
  n('Übung', 'die', 'alıştırma', 'exercise'),
  n('Wissen', 'das', 'bilgi', 'knowledge'),
  n('Studium', 'das', 'üniversite eğitimi', 'studies'),
  n('Kurs', 'der', 'kurs', 'course'),

  // ── Transport & travel ──────────────────────────────────────────────────────
  n('Fahrkarte', 'die', 'bilet (ulaşım)', 'ticket'),
  n('Lastwagen', 'der', 'kamyon', 'lorry, truck'),
  n('Haltestelle', 'die', 'durak', 'stop'),
  n('Hafen', 'der', 'liman', 'harbour'),
  n('Reise', 'die', 'yolculuk, seyahat', 'journey'),
  n('Ausflug', 'der', 'gezi', 'trip, excursion'),
  n('Koffer', 'der', 'bavul', 'suitcase'),
  n('Gepäck', 'das', 'bagaj', 'luggage'),
  n('Führerschein', 'der', 'sürücü belgesi, ehliyet', 'driving licence'),
  n('Parkplatz', 'der', 'otopark, park yeri', 'car park'),
  n('Unfall', 'der', 'kaza', 'accident'),
  n('Stau', 'der', 'trafik sıkışıklığı', 'traffic jam'),

  // ── Money & shopping ────────────────────────────────────────────────────────
  n('Rechnung', 'die', 'hesap, fatura', 'bill, invoice'),
  n('Quittung', 'die', 'makbuz, fiş', 'receipt'),
  n('Kasse', 'die', 'kasa', 'checkout, till'),
  n('Bargeld', 'das', 'nakit para', 'cash'),
  n('Münze', 'die', 'madenî para, bozuk para', 'coin'),
  n('Schein', 'der', 'kâğıt para, banknot', 'banknote'),
  n('Konto', 'das', 'hesap (banka)', 'account'),
  n('Kredit', 'der', 'kredi', 'loan, credit'),
  n('Rabatt', 'der', 'indirim', 'discount'),
  n('Angebot', 'das', 'teklif, kampanya', 'offer'),
  n('Kunde', 'der', 'müşteri', 'customer'),
  n('Verkäufer', 'der', 'satıcı', 'salesperson'),
  n('Einkauf', 'der', 'alışveriş', 'shopping, purchase'),

  // ── Health & medicine ───────────────────────────────────────────────────────
  n('Fieber', 'das', 'ateş (vücut)', 'fever'),
  n('Husten', 'der', 'öksürük', 'cough'),
  n('Erkältung', 'die', 'soğuk algınlığı', 'cold'),
  n('Medikament', 'das', 'ilaç', 'medication'),
  n('Tablette', 'die', 'hap, tablet', 'pill'),
  n('Praxis', 'die', 'muayenehane', 'doctor\'s office'),
  n('Behandlung', 'die', 'tedavi', 'treatment'),
  n('Verband', 'der', 'sargı, bandaj', 'bandage'),
  n('Spritze', 'die', 'iğne, enjeksiyon', 'injection'),
  n('Notaufnahme', 'die', 'acil servis', 'emergency room'),

  // ── Family & people ─────────────────────────────────────────────────────────
  n('Verwandte', 'der', 'akraba', 'relative'),
  n('Enkel', 'der', 'torun', 'grandchild'),
  n('Schwiegermutter', 'die', 'kayınvalide', 'mother-in-law'),
  n('Schwiegervater', 'der', 'kayınpeder', 'father-in-law'),
  n('Neffe', 'der', 'erkek yeğen', 'nephew'),
  n('Nichte', 'die', 'kız yeğen', 'niece'),
  n('Zwilling', 'der', 'ikiz', 'twin'),
  n('Ehe', 'die', 'evlilik', 'marriage'),
  n('Hochzeit', 'die', 'düğün', 'wedding'),
  n('Paar', 'das', 'çift', 'couple, pair'),
  n('Erwachsene', 'der', 'yetişkin', 'adult'),
  n('Jugendliche', 'der', 'genç, ergen', 'teenager'),
  n('Fremde', 'der', 'yabancı', 'stranger'),

  // ── Animals ─────────────────────────────────────────────────────────────────
  n('Mücke', 'die', 'sivrisinek', 'mosquito'),

  // ── Sports & hobbies ────────────────────────────────────────────────────────
  n('Mannschaft', 'die', 'takım', 'team'),
  n('Wettbewerb', 'der', 'yarışma', 'competition'),
  n('Training', 'das', 'antrenman', 'training'),
  n('Ball', 'der', 'top', 'ball'),
  n('Hobby', 'das', 'hobi', 'hobby'),
  n('Lied', 'das', 'şarkı', 'song'),
  n('Instrument', 'das', 'enstrüman, çalgı', 'instrument'),
  n('Gitarre', 'die', 'gitar', 'guitar'),
  n('Klavier', 'das', 'piyano', 'piano'),
  n('Film', 'der', 'film', 'film'),
  n('Roman', 'der', 'roman', 'novel'),

  // ── Time ────────────────────────────────────────────────────────────────────
  n('Augenblick', 'der', 'an, lahza', 'moment'),
  n('Vergangenheit', 'die', 'geçmiş', 'past'),
  n('Gegenwart', 'die', 'şimdiki zaman', 'present'),
  n('Zukunft', 'die', 'gelecek', 'future'),
  n('Jahrhundert', 'das', 'yüzyıl', 'century'),
  n('Feiertag', 'der', 'resmî tatil, bayram', 'public holiday'),
  n('Geburtstag', 'der', 'doğum günü', 'birthday'),
  n('Verspätung', 'die', 'gecikme', 'delay'),

  // ── Food & drink (more) ─────────────────────────────────────────────────────
  n('Frühstück', 'das', 'kahvaltı', 'breakfast'),
  n('Mittagessen', 'das', 'öğle yemeği', 'lunch'),
  n('Abendessen', 'das', 'akşam yemeği', 'dinner'),
  n('Getränk', 'das', 'içecek', 'drink'),
  n('Mineralwasser', 'das', 'maden suyu', 'mineral water'),
  n('Brötchen', 'das', 'küçük ekmek, sandviç ekmeği', 'bread roll'),
  n('Keks', 'der', 'bisküvi', 'biscuit'),
  n('Bonbon', 'das', 'şeker, bonbon', 'sweet, candy'),
  n('Müsli', 'das', 'müsli', 'muesli'),
  n('Nudeln', 'die', 'makarna', 'pasta, noodles'),
  n('Obst', 'das', 'meyve', 'fruit'),
  n('Gemüse', 'das', 'sebze', 'vegetable'),

  // ── Materials & substances ──────────────────────────────────────────────────
  n('Holz', 'das', 'odun, ahşap', 'wood'),
  n('Metall', 'das', 'metal', 'metal'),
  n('Eisen', 'das', 'demir', 'iron'),
  n('Gold', 'das', 'altın', 'gold'),
  n('Silber', 'das', 'gümüş', 'silver'),
  n('Plastik', 'das', 'plastik', 'plastic'),
  n('Stoff', 'der', 'kumaş; madde', 'fabric, material'),
  n('Leder', 'das', 'deri (malzeme)', 'leather'),
  n('Wolle', 'die', 'yün', 'wool'),
  n('Gummi', 'der', 'lastik, kauçuk', 'rubber'),
  n('Benzin', 'das', 'benzin', 'petrol'),
  n('Kohle', 'die', 'kömür', 'coal'),
  n('Staub', 'der', 'toz', 'dust'),
  n('Müll', 'der', 'çöp', 'rubbish'),
  n('Schmutz', 'der', 'kir, pislik', 'dirt'),

  // ── Plants & garden ─────────────────────────────────────────────────────────
  n('Samen', 'der', 'tohum', 'seed'),
  n('Rose', 'die', 'gül', 'rose'),
  n('Tanne', 'die', 'çam ağacı', 'fir tree'),
  n('Ernte', 'die', 'hasat, ürün', 'harvest'),

  // ── Society & government ────────────────────────────────────────────────────
  n('Staat', 'der', 'devlet', 'state'),
  n('Regierung', 'die', 'hükümet', 'government'),
  n('Recht', 'das', 'hak; hukuk', 'right; law'),
  n('Wahl', 'die', 'seçim', 'election, choice'),
  n('Partei', 'die', 'parti (siyasi)', 'party'),
  n('Polizei', 'die', 'polis', 'police'),
  n('Feuerwehr', 'die', 'itfaiye', 'fire brigade'),
  n('Steuer', 'die', 'vergi; (das) direksiyon', 'tax; (das) steering wheel'),
  n('Amt', 'das', 'resmî daire, makam', 'office, authority'),
  n('Ausweis', 'der', 'kimlik kartı', 'ID card'),
  n('Reisepass', 'der', 'pasaport', 'passport'),
  n('Botschaft', 'die', 'büyükelçilik; mesaj', 'embassy; message'),
  n('Gesellschaft', 'die', 'toplum', 'society'),
  n('Bevölkerung', 'die', 'nüfus', 'population'),
  n('Öffentlichkeit', 'die', 'kamuoyu, halk', 'public'),

  // ── Communication & information ─────────────────────────────────────────────
  n('Information', 'die', 'bilgi', 'information'),
  n('Mitteilung', 'die', 'bildiri, duyuru', 'notice'),
  n('Postkarte', 'die', 'kartpostal', 'postcard'),
  n('Paket', 'das', 'paket, koli', 'parcel'),
  n('Anruf', 'der', 'telefon araması', 'phone call'),
  n('Gespräch', 'das', 'konuşma, sohbet', 'conversation'),
  n('Text', 'der', 'metin', 'text'),
  n('Zeitschrift', 'die', 'dergi', 'magazine'),
  n('Bericht', 'der', 'rapor, haber', 'report'),
  n('Erklärung', 'die', 'açıklama', 'explanation'),

  // ── Abstract & society 2 ────────────────────────────────────────────────────
  n('Möglichkeit', 'die', 'olanak, imkân', 'possibility'),
  n('Vorteil', 'der', 'avantaj', 'advantage'),
  n('Nachteil', 'der', 'dezavantaj', 'disadvantage'),
  n('Unterschied', 'der', 'fark', 'difference'),
  n('Beziehung', 'die', 'ilişki', 'relationship'),
  n('Verantwortung', 'die', 'sorumluluk', 'responsibility'),
  n('Pflicht', 'die', 'görev, yükümlülük', 'duty'),
  n('Regel', 'die', 'kural', 'rule'),
  n('Zweck', 'der', 'amaç, maksat', 'purpose'),
  n('Wunsch', 'der', 'dilek, istek', 'wish'),
  n('Bedürfnis', 'das', 'gereksinim', 'need'),
  n('Wert', 'der', 'değer', 'value'),
  n('Vorschlag', 'der', 'öneri', 'suggestion'),
  n('Versuch', 'der', 'deneme, girişim', 'attempt'),
  n('Pech', 'das', 'şanssızlık', 'bad luck'),
  n('Mut', 'der', 'cesaret', 'courage'),
  n('Geduld', 'die', 'sabır', 'patience'),
  n('Stolz', 'der', 'gurur', 'pride'),
  n('Neugier', 'die', 'merak', 'curiosity'),
  n('Stimmung', 'die', 'ruh hâli, atmosfer', 'mood'),
  n('Charakter', 'der', 'karakter', 'character'),
  n('Eigenschaft', 'die', 'özellik', 'characteristic'),
  n('Gewohnheit', 'die', 'alışkanlık', 'habit'),
  n('Verhalten', 'das', 'davranış', 'behaviour'),

  // ── Measurement & quantity ──────────────────────────────────────────────────
  n('Größe', 'die', 'boy, beden', 'size'),
  n('Länge', 'die', 'uzunluk', 'length'),
  n('Breite', 'die', 'genişlik', 'width'),
  n('Höhe', 'die', 'yükseklik', 'height'),
  n('Gewicht', 'das', 'ağırlık', 'weight'),
  n('Menge', 'die', 'miktar', 'amount'),
  n('Anzahl', 'die', 'sayı, adet', 'number, count'),
  n('Hälfte', 'die', 'yarı', 'half'),
  n('Teil', 'der', 'parça, bölüm', 'part'),
  n('Stück', 'das', 'parça, tane', 'piece'),
  n('Dutzend', 'das', 'düzine', 'dozen'),
  n('Grad', 'der', 'derece', 'degree'),
  n('Liter', 'der', 'litre', 'litre'),
  n('Kilogramm', 'das', 'kilogram', 'kilogram'),
  n('Meter', 'der', 'metre', 'metre'),
  n('Kilometer', 'der', 'kilometre', 'kilometre'),
  n('Prozent', 'das', 'yüzde', 'percent'),

  // ── House parts & places ────────────────────────────────────────────────────
  n('Aufzug', 'der', 'asansör', 'lift, elevator'),
  n('Flur', 'der', 'koridor, antre', 'hallway'),
  n('Keller', 'der', 'bodrum', 'cellar'),
  n('Etage', 'die', 'kat', 'floor, storey'),
  n('Heizung', 'die', 'kalorifer, ısıtma', 'heating'),
  n('Steckdose', 'die', 'priz', 'socket'),
  n('Schalter', 'der', 'düğme, anahtar (elektrik); gişe', 'switch; counter'),
  n('Klingel', 'die', 'zil', 'doorbell'),
  n('Werkzeug', 'das', 'alet', 'tool'),
  n('Leiter', 'die', 'merdiven; (der) lider, yönetici', 'ladder; (der) leader'),
  n('Garage', 'die', 'garaj', 'garage'),
  n('Balkon', 'der', 'balkon', 'balcony'),

  // ── Professions (more) ──────────────────────────────────────────────────────
  n('Zahnarzt', 'der', 'diş hekimi', 'dentist'),
  n('Apotheker', 'der', 'eczacı', 'pharmacist'),
  n('Verkäuferin', 'die', 'satıcı (kadın)', 'saleswoman'),
  n('Kellner', 'der', 'garson', 'waiter'),
  n('Mechaniker', 'der', 'tamirci', 'mechanic'),
  n('Elektriker', 'der', 'elektrikçi', 'electrician'),
  n('Tischler', 'der', 'marangoz', 'carpenter'),
  n('Maler', 'der', 'boyacı; ressam', 'painter'),
  n('Architekt', 'der', 'mimar', 'architect'),
  n('Wissenschaftler', 'der', 'bilim insanı', 'scientist'),
  n('Forscher', 'der', 'araştırmacı', 'researcher'),
  n('Journalist', 'der', 'gazeteci', 'journalist'),
  n('Übersetzer', 'der', 'çevirmen', 'translator'),
  n('Dolmetscher', 'der', 'tercüman (sözlü)', 'interpreter'),
  n('Fahrer', 'der', 'şoför, sürücü', 'driver'),
  n('Briefträger', 'der', 'postacı', 'postman'),
  n('Feuerwehrmann', 'der', 'itfaiyeci', 'firefighter'),
  n('Trainer', 'der', 'antrenör', 'coach'),
  n('Berater', 'der', 'danışman', 'advisor'),
  n('Direktor', 'der', 'müdür', 'director'),
  n('Sekretär', 'der', 'sekreter', 'secretary'),

  // ── Emotions & mind ─────────────────────────────────────────────────────────
  n('Trauer', 'die', 'üzüntü, yas', 'grief'),
  n('Wut', 'die', 'öfke', 'anger'),
  n('Sorge', 'die', 'endişe, kaygı', 'worry'),
  n('Stress', 'der', 'stres', 'stress'),
  n('Überraschung', 'die', 'sürpriz', 'surprise'),
  n('Langeweile', 'die', 'can sıkıntısı', 'boredom'),
  n('Lust', 'die', 'istek, heves', 'desire'),
  n('Liebe', 'die', 'sevgi, aşk', 'love'),
  n('Hass', 'der', 'nefret', 'hatred'),
  n('Eifersucht', 'die', 'kıskançlık', 'jealousy'),
  n('Vertrauen', 'das', 'güven', 'trust'),
  n('Zweifel', 'der', 'şüphe', 'doubt'),
  n('Aufmerksamkeit', 'die', 'dikkat', 'attention'),
  n('Fantasie', 'die', 'hayal gücü', 'imagination'),
  n('Vernunft', 'die', 'akıl, mantık', 'reason'),
  n('Bewusstsein', 'das', 'bilinç', 'consciousness'),

  // ── Events & occasions ──────────────────────────────────────────────────────
  n('Ereignis', 'das', 'olay', 'event'),
  n('Veranstaltung', 'die', 'etkinlik', 'event, function'),
  n('Feier', 'die', 'kutlama', 'celebration'),
  n('Fest', 'das', 'şenlik, bayram', 'festival'),
  n('Party', 'die', 'parti', 'party'),
  n('Konzert', 'das', 'konser', 'concert'),
  n('Vorstellung', 'die', 'gösteri; tanıtım', 'performance'),
  n('Ausstellung', 'die', 'sergi', 'exhibition'),
  n('Treffen', 'das', 'buluşma', 'meeting'),
  n('Sitzung', 'die', 'oturum, toplantı', 'session'),
  n('Konferenz', 'die', 'konferans', 'conference'),
  n('Unterhaltung', 'die', 'eğlence; sohbet', 'entertainment'),
  n('Demonstration', 'die', 'gösteri, protesto', 'demonstration'),

  // ── Science & nature ────────────────────────────────────────────────────────
  n('Wissenschaft', 'die', 'bilim', 'science'),
  n('Forschung', 'die', 'araştırma', 'research'),
  n('Energie', 'die', 'enerji', 'energy'),
  n('Licht', 'das', 'ışık', 'light'),
  n('Schatten', 'der', 'gölge', 'shadow'),
  n('Hitze', 'die', 'sıcaklık (aşırı)', 'heat'),
  n('Kälte', 'die', 'soğuk', 'cold'),
  n('Rauch', 'der', 'duman', 'smoke'),
  n('Gas', 'das', 'gaz', 'gas'),
  n('Temperatur', 'die', 'sıcaklık', 'temperature'),
  n('Klima', 'das', 'iklim', 'climate'),
  n('Weltall', 'das', 'uzay, evren', 'universe'),
  n('Planet', 'der', 'gezegen', 'planet'),
  n('Ozean', 'der', 'okyanus', 'ocean'),
  n('Küste', 'die', 'kıyı, sahil', 'coast'),
  n('Welle', 'die', 'dalga', 'wave'),

  // ── Geography & places ──────────────────────────────────────────────────────
  n('Gegend', 'die', 'bölge, yöre', 'area'),
  n('Region', 'die', 'bölge', 'region'),
  n('Stadtteil', 'der', 'şehir semti', 'district'),
  n('Richtung', 'die', 'yön', 'direction'),
  n('Umgebung', 'die', 'çevre, etraf', 'surroundings'),
  n('Aussicht', 'die', 'manzara', 'view'),

  // ── Kitchen & food (more) ───────────────────────────────────────────────────
  n('Kühlschrank', 'der', 'buzdolabı', 'fridge'),
  n('Herd', 'der', 'ocak', 'cooker, stove'),
  n('Wasserhahn', 'der', 'musluk', 'tap'),
  n('Korken', 'der', 'mantar tıpa', 'cork'),
  n('Deckel', 'der', 'kapak', 'lid'),
  n('Serviette', 'die', 'peçete', 'napkin'),
  n('Tablett', 'das', 'tepsi', 'tray'),
  n('Glasur', 'die', 'glazür', 'glaze, icing'),
  n('Portion', 'die', 'porsiyon', 'portion'),
  n('Rezept', 'das', 'tarif; reçete', 'recipe; prescription'),
  n('Geschmack', 'der', 'tat, lezzet', 'taste'),
  n('Hunger', 'der', 'açlık', 'hunger'),
  n('Durst', 'der', 'susuzluk', 'thirst'),
  n('Diät', 'die', 'diyet', 'diet'),

  // ── Objects & misc ──────────────────────────────────────────────────────────
  n('Gegenstand', 'der', 'eşya, nesne', 'object'),
  n('Ding', 'das', 'şey', 'thing'),
  n('Karton', 'der', 'karton kutu', 'cardboard box'),
  n('Tüte', 'die', 'poşet, torba', 'bag'),
  n('Schachtel', 'die', 'kutu', 'box'),
  n('Dose', 'die', 'konserve kutusu', 'tin, can'),
  n('Schnur', 'die', 'ip, sicim', 'string'),
  n('Draht', 'der', 'tel', 'wire'),
  n('Nadel', 'die', 'iğne', 'needle'),
  n('Faden', 'der', 'iplik', 'thread'),
  n('Streichholz', 'das', 'kibrit', 'match'),
  n('Klebstoff', 'der', 'yapıştırıcı', 'glue'),
  n('Geschenk', 'das', 'hediye', 'gift'),
  n('Spielzeug', 'das', 'oyuncak', 'toy'),
  n('Puppe', 'die', 'oyuncak bebek', 'doll'),

  // ── Multi-meaning nouns — bulk dict picks one sense; the curated entry
  //    spells out both so the right one is always visible. (Bank, Steuer,
  //    Leiter already covered earlier in this file / base list.)
  n('Mutter', 'die', 'anne; (teknik) somun', 'mother; (tech) nut'),
  n('Strauß', 'der', 'çiçek buketi; deve kuşu', 'bouquet; ostrich'),
  n('Kiefer', 'die', 'çene (eril: çam ağacı)', 'jaw; (m.) pine tree'),
  n('Schale', 'die', 'kase; kabuk (meyve)', 'bowl; peel'),
  n('Pension', 'die', 'pansiyon; emekli maaşı', 'guesthouse; pension'),
  n('Schimmel', 'der', 'küf; beyaz at', 'mould; white horse'),

  // ── Body (more) ─────────────────────────────────────────────────────────────
  n('Stirn', 'die', 'alın', 'forehead'),
  n('Wange', 'die', 'yanak', 'cheek'),
  n('Kinn', 'das', 'çene', 'chin'),
  n('Augenbraue', 'die', 'kaş', 'eyebrow'),
  n('Wimper', 'die', 'kirpik', 'eyelash'),
  n('Ellenbogen', 'der', 'dirsek', 'elbow'),
  n('Handgelenk', 'das', 'bilek', 'wrist'),
  n('Faust', 'die', 'yumruk', 'fist'),
  n('Ferse', 'die', 'topuk', 'heel'),
  n('Zeh', 'der', 'ayak parmağı', 'toe'),
  n('Waden', 'die', 'baldır', 'calf'),
  n('Rippe', 'die', 'kaburga', 'rib'),
  n('Muskel', 'der', 'kas', 'muscle'),
  n('Leber', 'die', 'karaciğer', 'liver'),
  n('Niere', 'die', 'böbrek', 'kidney'),
  n('Ader', 'die', 'damar', 'vein'),
  n('Atem', 'der', 'nefes', 'breath'),

  // ── Law & justice ───────────────────────────────────────────────────────────
  n('Gericht', 'das', 'mahkeme; yemek', 'court; dish'),
  n('Urteil', 'das', 'hüküm, karar', 'verdict'),
  n('Strafe', 'die', 'ceza', 'punishment'),
  n('Geldstrafe', 'die', 'para cezası', 'fine'),
  n('Verbrechen', 'das', 'suç', 'crime'),
  n('Dieb', 'der', 'hırsız', 'thief'),
  n('Diebstahl', 'der', 'hırsızlık', 'theft'),
  n('Zeuge', 'der', 'tanık', 'witness'),
  n('Beweis', 'der', 'kanıt, delil', 'proof'),
  n('Schuld', 'die', 'suç, kabahat; borç', 'guilt; debt'),
  n('Opfer', 'das', 'kurban', 'victim'),
  n('Gefängnis', 'das', 'hapishane', 'prison'),
  n('Anklage', 'die', 'iddianame, suçlama', 'accusation'),
  n('Verteidigung', 'die', 'savunma', 'defence'),
  n('Erlaubnis', 'die', 'izin', 'permission'),
  n('Verbot', 'das', 'yasak', 'ban'),

  // ── Finance & economy ───────────────────────────────────────────────────────
  n('Wirtschaft', 'die', 'ekonomi', 'economy'),
  n('Handel', 'der', 'ticaret', 'trade'),
  n('Industrie', 'die', 'sanayi', 'industry'),
  n('Firma', 'die', 'firma, şirket', 'company'),
  n('Unternehmen', 'das', 'işletme, şirket', 'enterprise'),
  n('Gewinn', 'der', 'kâr', 'profit'),
  n('Verlust', 'der', 'zarar, kayıp', 'loss'),
  n('Schulden', 'die', 'borçlar', 'debts'),
  n('Vermögen', 'das', 'servet, varlık', 'fortune, assets'),
  n('Investition', 'die', 'yatırım', 'investment'),
  n('Versicherung', 'die', 'sigorta', 'insurance'),
  n('Zins', 'der', 'faiz', 'interest'),
  n('Währung', 'die', 'para birimi', 'currency'),
  n('Aktie', 'die', 'hisse senedi', 'share, stock'),
  n('Budget', 'das', 'bütçe', 'budget'),
  n('Ausgabe', 'die', 'harcama; baskı', 'expense; edition'),
  n('Einnahme', 'die', 'gelir, hasılat', 'revenue'),
  n('Geldbeutel', 'der', 'cüzdan, para kesesi', 'purse'),
  n('Brieftasche', 'die', 'cüzdan', 'wallet'),

  // ── Education & academia ────────────────────────────────────────────────────
  n('Bildung', 'die', 'eğitim', 'education'),
  n('Grundschule', 'die', 'ilkokul', 'primary school'),
  n('Vorlesung', 'die', 'ders (üniversite)', 'lecture'),
  n('Seminar', 'das', 'seminer', 'seminar'),
  n('Professor', 'der', 'profesör', 'professor'),
  n('Abschluss', 'der', 'diploma, mezuniyet', 'degree, graduation'),
  n('Zeugnis', 'das', 'karne, belge', 'report card, certificate'),
  n('Diplom', 'das', 'diploma', 'diploma'),
  n('Fach', 'das', 'ders, branş; göz, raf', 'subject; compartment'),
  n('Wissenschaftlerin', 'die', 'bilim insanı (kadın)', 'scientist (f.)'),
  n('Thema', 'das', 'konu', 'topic'),
  n('Kapitel', 'das', 'bölüm (kitap)', 'chapter'),
  n('Inhalt', 'der', 'içerik', 'content'),
  n('Titel', 'der', 'başlık; unvan', 'title'),
  n('Seite', 'die', 'sayfa; taraf', 'page; side'),
  n('Aufsatz', 'der', 'kompozisyon, makale', 'essay'),
  n('Vortrag', 'der', 'sunum, konuşma', 'presentation'),
  n('Pädagoge', 'der', 'eğitimci', 'educator'),

  // ── Arts & culture ──────────────────────────────────────────────────────────
  n('Gemälde', 'das', 'tablo, resim', 'painting'),
  n('Zeichnung', 'die', 'çizim', 'drawing'),
  n('Skulptur', 'die', 'heykel', 'sculpture'),
  n('Bühne', 'die', 'sahne', 'stage'),
  n('Schauspielerin', 'die', 'oyuncu (kadın)', 'actress'),
  n('Publikum', 'das', 'seyirci, izleyici', 'audience'),
  n('Künstlerin', 'die', 'sanatçı (kadın)', 'artist (f.)'),
  n('Dichter', 'der', 'şair', 'poet'),
  n('Gedicht', 'das', 'şiir', 'poem'),
  n('Märchen', 'das', 'masal', 'fairy tale'),
  n('Kapelle', 'die', 'küçük orkestra; şapel', 'band; chapel'),
  n('Melodie', 'die', 'melodi, ezgi', 'melody'),
  n('Ton', 'der', 'ses, ton; kil', 'sound, tone; clay'),
  n('Tanz', 'der', 'dans', 'dance'),
  n('Trommel', 'die', 'davul', 'drum'),
  n('Flöte', 'die', 'flüt', 'flute'),
  n('Geige', 'die', 'keman', 'violin'),

  // ── Communication & technology (more) ───────────────────────────────────────
  n('Laptop', 'der', 'dizüstü bilgisayar', 'laptop'),
  n('Internet', 'das', 'internet', 'internet'),
  n('Webseite', 'die', 'web sitesi', 'website'),
  n('Überweisung', 'die', 'havale', 'bank transfer'),
  n('Passwort', 'das', 'şifre', 'password'),
  n('Adresse', 'die', 'adres', 'address'),
  n('Nummer', 'die', 'numara', 'number'),
  n('Bildschirmfoto', 'das', 'ekran görüntüsü', 'screenshot'),
  n('Stecker', 'der', 'fiş', 'plug'),
  n('Signal', 'das', 'sinyal', 'signal'),
  n('Netzwerk', 'das', 'ağ', 'network'),
  n('Software', 'die', 'yazılım', 'software'),
  n('Speicher', 'der', 'bellek, depolama', 'memory, storage'),
  n('Bildschirmschoner', 'der', 'ekran koruyucu', 'screensaver'),
  n('Roboter', 'der', 'robot', 'robot'),

  // ── Travel & places (more) ──────────────────────────────────────────────────
  n('Empfang', 'der', 'resepsiyon; karşılama', 'reception'),
  n('Aufenthalt', 'der', 'konaklama, kalış', 'stay'),
  n('Ausland', 'das', 'yurt dışı', 'abroad'),
  n('Heimat', 'die', 'memleket, yurt', 'homeland'),
  n('Sehenswürdigkeit', 'die', 'gezilecek yer', 'sight, attraction'),
  n('Denkmal', 'das', 'anıt', 'monument'),
  n('Tankstelle', 'die', 'benzin istasyonu', 'petrol station'),
  n('Werkstatt', 'die', 'tamirhane, atölye', 'workshop'),
  n('Baustelle', 'die', 'şantiye, inşaat alanı', 'construction site'),
  n('Friedhof', 'der', 'mezarlık', 'cemetery'),
  n('Zelt', 'das', 'çadır', 'tent'),
  n('Unterkunft', 'die', 'konaklama yeri', 'accommodation'),
  n('Wegweiser', 'der', 'yön levhası', 'signpost'),
  n('Rolltreppe', 'die', 'yürüyen merdiven', 'escalator'),
  n('Gehweg', 'der', 'kaldırım', 'pavement'),
  n('Kreuzung', 'die', 'kavşak', 'crossroads'),
  n('Ampel', 'die', 'trafik ışığı', 'traffic light'),

  // ── Weather & nature (more) ─────────────────────────────────────────────────
  n('Donner', 'der', 'gök gürültüsü', 'thunder'),
  n('Hagel', 'der', 'dolu', 'hail'),
  n('Regenbogen', 'der', 'gökkuşağı', 'rainbow'),
  n('Tau', 'der', 'çiy', 'dew'),
  n('Frost', 'der', 'don, ayaz', 'frost'),
  n('Überschwemmung', 'die', 'sel, su baskını', 'flood'),
  n('Erdbeben', 'das', 'deprem', 'earthquake'),
  n('Vulkan', 'der', 'yanardağ', 'volcano'),
  n('Hügel', 'der', 'tepe', 'hill'),
  n('Gipfel', 'der', 'zirve, doruk', 'summit'),
  n('Quelle', 'die', 'kaynak; pınar', 'source; spring'),
  n('Teich', 'der', 'gölet, havuz', 'pond'),
  n('Bach', 'der', 'dere', 'stream'),
  n('Ufer', 'das', 'kıyı, kenar', 'shore, bank'),
  n('Landschaft', 'die', 'manzara, peyzaj', 'landscape'),
  n('Umweltschutz', 'der', 'çevre koruma', 'environmental protection'),

  // ── Animals (more) ──────────────────────────────────────────────────────────
  n('Adler', 'der', 'kartal', 'eagle'),
  n('Eule', 'die', 'baykuş', 'owl'),
  n('Taube', 'die', 'güvercin', 'pigeon'),
  n('Möwe', 'die', 'martı', 'seagull'),
  n('Hahn', 'der', 'horoz', 'rooster'),
  n('Esel', 'der', 'eşek', 'donkey'),
  n('Fuchs', 'der', 'tilki', 'fox'),
  n('Hirsch', 'der', 'geyik', 'deer'),
  n('Schildkröte', 'die', 'kaplumbağa', 'turtle'),
  n('Krokodil', 'das', 'timsah', 'crocodile'),
  n('Wal', 'der', 'balina', 'whale'),
  n('Hai', 'der', 'köpekbalığı', 'shark'),
  n('Krabbe', 'die', 'yengeç', 'crab'),
  n('Fliege', 'die', 'sinek', 'fly'),
  n('Wurm', 'der', 'solucan', 'worm'),

  // ── Food & drink (more) ─────────────────────────────────────────────────────
  n('Zutat', 'die', 'malzeme (yemek)', 'ingredient'),
  n('Sandwich', 'das', 'sandviç', 'sandwich'),
  n('Pizza', 'die', 'pizza', 'pizza'),
  n('Pommes', 'die', 'patates kızartması', 'chips, fries'),
  n('Eintopf', 'der', 'güveç', 'stew'),
  n('Braten', 'der', 'kızartma, rosto', 'roast'),
  n('Schinken', 'der', 'jambon', 'ham'),
  n('Speck', 'der', 'domuz pastırması', 'bacon'),
  n('Pfannkuchen', 'der', 'krep, gözleme', 'pancake'),
  n('Sahnetorte', 'die', 'kremalı pasta', 'cream cake'),
  n('Pudding', 'der', 'puding', 'pudding'),
  n('Sirup', 'der', 'şurup', 'syrup'),
  n('Essig', 'der', 'sirke', 'vinegar'),
  n('Senf', 'der', 'hardal', 'mustard'),
  n('Beere', 'die', 'üzümsü meyve', 'berry'),
  n('Pflaume', 'die', 'erik', 'plum'),
  n('Pfirsich', 'der', 'şeftali', 'peach'),
  n('Aprikose', 'die', 'kayısı', 'apricot'),
  n('Melone', 'die', 'kavun, karpuz', 'melon'),
  n('Ananas', 'die', 'ananas', 'pineapple'),
  n('Kohl', 'der', 'lahana', 'cabbage'),
  n('Spinat', 'der', 'ıspanak', 'spinach'),
  n('Bohne', 'die', 'fasulye', 'bean'),
  n('Erbse', 'die', 'bezelye', 'pea'),
  n('Mais', 'der', 'mısır', 'corn'),
  n('Paprika', 'die', 'biber (sebze)', 'bell pepper'),

  // ── Clothing & accessories (more) ───────────────────────────────────────────
  n('Kleidung', 'die', 'giysi, kıyafet', 'clothing'),
  n('Anzug', 'der', 'takım elbise', 'suit'),
  n('Bluse', 'die', 'bluz', 'blouse'),
  n('Weste', 'die', 'yelek', 'vest'),
  n('Sandale', 'die', 'sandalet', 'sandal'),
  n('Rucksack', 'der', 'sırt çantası', 'backpack'),
  n('Geldbörse', 'die', 'cüzdan', 'wallet'),
  n('Ring', 'der', 'yüzük', 'ring'),
  n('Kette', 'die', 'kolye; zincir', 'necklace; chain'),
  n('Ohrring', 'der', 'küpe', 'earring'),
  n('Armband', 'das', 'bileklik', 'bracelet'),
  n('Schmuck', 'der', 'takı, mücevher', 'jewellery'),
  n('Reißverschluss', 'der', 'fermuar', 'zip'),
  n('Schultasche', 'die', 'okul çantası', 'school bag'),
  n('Kragen', 'der', 'yaka', 'collar'),
  n('Stoffmuster', 'das', 'kumaş deseni', 'fabric pattern'),

  // ── Abstract & social (more) ────────────────────────────────────────────────
  n('Geburt', 'die', 'doğum', 'birth'),
  n('Jugend', 'die', 'gençlik', 'youth'),
  n('Alter', 'das', 'yaş; yaşlılık', 'age'),
  n('Kindheit', 'die', 'çocukluk', 'childhood'),
  n('Schicksal', 'das', 'kader', 'fate'),
  n('Zufall', 'der', 'tesadüf', 'coincidence'),
  n('Wirklichkeit', 'die', 'gerçeklik', 'reality'),
  n('Bedeutung', 'die', 'anlam, önem', 'meaning'),
  n('Ursache', 'die', 'sebep', 'cause'),
  n('Folge', 'die', 'sonuç; bölüm (dizi)', 'consequence; episode'),
  n('Wirkung', 'die', 'etki', 'effect'),
  n('Zusammenhang', 'der', 'bağlam, ilişki', 'context'),
  n('Vorbild', 'das', 'örnek, rol model', 'role model'),
  n('Vorurteil', 'das', 'önyargı', 'prejudice'),
  n('Gerechtigkeit', 'die', 'adalet', 'justice'),
  n('Gleichheit', 'die', 'eşitlik', 'equality'),
  n('Würde', 'die', 'onur, haysiyet', 'dignity'),
  n('Ehre', 'die', 'onur, şeref', 'honour'),
  n('Respekt', 'der', 'saygı', 'respect'),
  n('Rücksicht', 'die', 'saygı, anlayış', 'consideration'),
  n('Zuneigung', 'die', 'sevgi, yakınlık', 'affection'),
  n('Hilfe', 'die', 'yardım', 'help'),
  n('Unterstützung', 'die', 'destek', 'support'),
  n('Einfluss', 'der', 'etki, nüfuz', 'influence'),
  n('Routine', 'die', 'rutin, alışılmış düzen', 'routine'),
  n('Fortschritt', 'der', 'ilerleme', 'progress'),
  n('Entwicklung', 'die', 'gelişme', 'development'),
  n('Veränderung', 'die', 'değişiklik', 'change'),
  n('Zustand', 'der', 'durum, hâl', 'condition, state'),
  n('Lage', 'die', 'durum; konum', 'situation; location'),
  n('Umstand', 'der', 'koşul, durum', 'circumstance'),
  n('Bereich', 'der', 'alan, saha', 'area, field'),
  n('Aspekt', 'der', 'yön, açı', 'aspect'),
  n('Absicht', 'die', 'niyet, kasıt', 'intention'),

  // ── Tools, objects & misc (more) ────────────────────────────────────────────
  n('Hammer', 'der', 'çekiç', 'hammer'),
  n('Säge', 'die', 'testere', 'saw'),
  n('Bohrer', 'der', 'matkap', 'drill'),
  n('Schraube', 'die', 'vida', 'screw'),
  n('Nagel', 'der', 'çivi; tırnak', 'nail'),
  n('Zange', 'die', 'pense, kerpeten', 'pliers'),
  n('Schraubenzieher', 'der', 'tornavida', 'screwdriver'),
  n('Pinsel', 'der', 'fırça', 'brush'),
  n('Türklinke', 'die', 'kapı kolu', 'door handle'),
  n('Griff', 'der', 'tutamak, kulp', 'handle'),
  n('Haken', 'der', 'kanca', 'hook'),
  n('Kabel', 'das', 'kablo', 'cable'),
  n('Batterie', 'die', 'pil', 'battery'),
  n('Glühbirne', 'die', 'ampul', 'light bulb'),
  n('Taschenlampe', 'die', 'el feneri', 'torch'),
  n('Schirm', 'der', 'şemsiye', 'umbrella'),
  n('Fächer', 'der', 'yelpaze', 'fan'),
  n('Spielkarte', 'die', 'oyun kâğıdı', 'playing card'),
  n('Würfel', 'der', 'zar; küp', 'dice; cube'),
  n('Ballon', 'der', 'balon', 'balloon'),
  n('Korb', 'der', 'sepet', 'basket'),
  n('Fass', 'das', 'fıçı, varil', 'barrel'),
  n('Kiste', 'die', 'sandık, kasa', 'crate'),
  n('Kanne', 'die', 'demlik, sürahi', 'pot, jug'),
  n('Vase', 'die', 'vazo', 'vase'),
  n('Rahmen', 'der', 'çerçeve', 'frame'),
  n('Brett', 'das', 'tahta levha', 'board, plank'),
  n('Stange', 'die', 'çubuk, sırık', 'pole, rod'),
  n('Decke', 'die', 'battaniye; tavan', 'blanket; ceiling'),

  // ── Final batch — everyday & intermediate ───────────────────────────────────
  n('Ankunft', 'die', 'varış', 'arrival'),
  n('Abfahrt', 'die', 'hareket, kalkış', 'departure'),
  n('Aufenthaltsraum', 'der', 'dinlenme odası', 'lounge'),
  n('Notfall', 'der', 'acil durum', 'emergency'),
  n('Vorsicht', 'die', 'dikkat, ihtiyat', 'caution'),
  n('Rettung', 'die', 'kurtarma', 'rescue'),
  n('Lärm', 'der', 'gürültü', 'noise'),
  n('Ruhe', 'die', 'sessizlik, huzur', 'quiet, calm'),
  n('Ordnung', 'die', 'düzen', 'order'),
  n('Unordnung', 'die', 'düzensizlik, dağınıklık', 'mess'),
  n('Sauberkeit', 'die', 'temizlik', 'cleanliness'),
  n('Reihe', 'die', 'sıra, dizi', 'row, series'),
  n('Reihenfolge', 'die', 'sıralama, dizilim', 'sequence'),
  n('Anfang', 'der', 'başlangıç', 'beginning'),
  n('Ende', 'das', 'son, bitiş', 'end'),
  n('Mitte', 'die', 'orta', 'middle'),
  n('Rand', 'der', 'kenar', 'edge'),
  n('Höhepunkt', 'der', 'doruk noktası', 'climax, peak'),
  n('Mehrheit', 'die', 'çoğunluk', 'majority'),
  n('Minderheit', 'die', 'azınlık', 'minority'),
  n('Durchschnitt', 'der', 'ortalama', 'average'),
  n('Gewohnheitstier', 'das', 'alışkanlıklarına bağlı kişi', 'creature of habit'),
  n('Geheimnis', 'das', 'sır', 'secret'),
  n('Erwartung', 'die', 'beklenti', 'expectation'),
  n('Auswahl', 'die', 'seçim, çeşit', 'selection'),
  n('Vielfalt', 'die', 'çeşitlilik', 'diversity'),
  n('Mangel', 'der', 'eksiklik, kıtlık', 'lack, shortage'),
  n('Überfluss', 'der', 'bolluk', 'abundance'),
  n('Vorrat', 'der', 'stok, erzak', 'supply, stock'),
  n('Bedarf', 'der', 'ihtiyaç, talep', 'demand, need'),
  n('Nutzen', 'der', 'fayda, yarar', 'benefit'),
  n('Schaden', 'der', 'hasar, zarar', 'damage'),
  n('Risiko', 'das', 'risk', 'risk'),
  n('Sicherheit', 'die', 'güvenlik; emniyet', 'safety, security'),
  n('Genauigkeit', 'die', 'kesinlik, titizlik', 'accuracy'),
  n('Geschwindigkeit', 'die', 'hız', 'speed'),
  n('Abstand', 'der', 'mesafe, ara', 'distance, gap'),
  n('Richtungswechsel', 'der', 'yön değişikliği', 'change of direction'),
  n('Fortschrittsbericht', 'der', 'ilerleme raporu', 'progress report'),
  n('Zusammenfassung', 'die', 'özet', 'summary'),
  n('Einzelheit', 'die', 'ayrıntı', 'detail'),
  n('Übersicht', 'die', 'genel bakış', 'overview'),
  n('Hinweis', 'der', 'ipucu, uyarı', 'hint, notice'),
  n('Ratschlag', 'der', 'öğüt, tavsiye', 'advice'),
  n('Mühe', 'die', 'çaba, zahmet', 'effort'),
  n('Anstrengung', 'die', 'gayret, çaba', 'exertion'),
  n('Leistung', 'die', 'performans, başarım', 'performance'),
  n('Fähigkeit', 'die', 'yetenek, beceri', 'ability'),
  n('Begabung', 'die', 'kabiliyet', 'talent'),
  n('Schwäche', 'die', 'zayıflık, zaaf', 'weakness'),
  n('Stärke', 'die', 'güç, kuvvet', 'strength'),
];
