// Extended German adjective bank — batch 4 of the curated expansion.
// Common A2/B1 adjectives with hand-checked Turkish meanings.
import type { CuratedWord } from '@/lib/mock-data';

const adj = (word: string, tr: string, en: string): CuratedWord => ({
  id: word,
  word,
  language: 'de',
  type: 'adjective',
  shortDef: { tr, en },
});

export const GERMAN_ADJECTIVES_EXTRA: CuratedWord[] = [
  // ── Character & behaviour ───────────────────────────────────────────────────
  adj('ehrlich', 'dürüst', 'honest'),
  adj('mutig', 'cesur', 'brave'),
  adj('geduldig', 'sabırlı', 'patient'),
  adj('großzügig', 'cömert', 'generous'),
  adj('geizig', 'cimri', 'stingy'),
  adj('selbstbewusst', 'özgüvenli', 'confident'),
  adj('schüchtern', 'utangaç', 'shy'),
  adj('neugierig', 'meraklı', 'curious'),
  adj('vorsichtig', 'dikkatli, tedbirli', 'careful'),
  adj('zuverlässig', 'güvenilir', 'reliable'),
  adj('pünktlich', 'dakik', 'punctual'),
  adj('ordentlich', 'düzenli, tertipli', 'tidy'),
  adj('streng', 'sert, katı', 'strict'),
  adj('stolz', 'gururlu', 'proud'),
  adj('eifersüchtig', 'kıskanç', 'jealous'),
  adj('egoistisch', 'bencil', 'selfish'),
  adj('hilfsbereit', 'yardımsever', 'helpful'),
  adj('sportlich', 'sportif', 'sporty, athletic'),
  adj('begabt', 'yetenekli', 'talented'),
  adj('verrückt', 'çılgın, deli', 'crazy'),

  // ── Feelings & states ───────────────────────────────────────────────────────
  adj('zufrieden', 'memnun, hoşnut', 'satisfied'),
  adj('aufgeregt', 'heyecanlı', 'excited'),
  adj('enttäuscht', 'hayal kırıklığına uğramış', 'disappointed'),
  adj('verliebt', 'âşık', 'in love'),
  adj('einsam', 'yalnız', 'lonely'),
  adj('ängstlich', 'ürkek, korkak', 'anxious'),
  adj('überrascht', 'şaşırmış', 'surprised'),
  adj('erschöpft', 'bitkin, tükenmiş', 'exhausted'),
  adj('wach', 'uyanık', 'awake'),
  adj('verwirrt', 'kafası karışmış', 'confused'),
  adj('gespannt', 'merakla bekleyen', 'eager, curious'),
  adj('besorgt', 'endişeli', 'worried'),
  adj('entspannt', 'rahat, gevşemiş', 'relaxed'),
  adj('gelangweilt', 'sıkılmış', 'bored'),
  adj('dankbar', 'minnettar', 'grateful'),

  // ── Quality & appearance ────────────────────────────────────────────────────
  adj('schön', 'güzel', 'beautiful'),
  adj('hübsch', 'şirin, sevimli', 'pretty'),
  adj('gepflegt', 'bakımlı', 'well-groomed'),
  adj('elegant', 'şık, zarif', 'elegant'),
  adj('altmodisch', 'eski moda', 'old-fashioned'),
  adj('praktisch', 'pratik, kullanışlı', 'practical'),
  adj('nützlich', 'faydalı', 'useful'),
  adj('nutzlos', 'işe yaramaz', 'useless'),
  adj('wertvoll', 'değerli', 'valuable'),
  adj('zerbrechlich', 'kırılgan', 'fragile'),
  adj('glatt', 'pürüzsüz, kaygan', 'smooth, slippery'),
  adj('rau', 'pürüzlü, sert', 'rough'),
  adj('spitz', 'sivri', 'pointed'),
  adj('rund', 'yuvarlak', 'round'),
  adj('eckig', 'köşeli', 'angular'),
  adj('flach', 'düz, sığ', 'flat, shallow'),
  adj('eng', 'dar', 'narrow, tight'),
  adj('locker', 'gevşek, rahat', 'loose'),
  adj('scharf', 'keskin; acı (baharat)', 'sharp; spicy'),
  adj('frisch', 'taze', 'fresh'),

  // ── Situation & judgement ───────────────────────────────────────────────────
  adj('unmöglich', 'imkânsız', 'impossible'),
  adj('sicher', 'emin; güvenli', 'sure; safe'),
  adj('gefährlich', 'tehlikeli', 'dangerous'),
  adj('ähnlich', 'benzer', 'similar'),
  adj('gleich', 'aynı, eşit', 'same, equal'),
  adj('verschieden', 'farklı, çeşitli', 'different'),
  adj('speziell', 'özel, belirli', 'special'),
  adj('normal', 'normal', 'normal'),
  adj('üblich', 'alışılmış, olağan', 'usual'),
  adj('seltsam', 'tuhaf, garip', 'strange'),
  adj('komisch', 'tuhaf; komik', 'odd, funny'),
  adj('deutlich', 'belirgin, açık', 'clear, distinct'),
  adj('klar', 'açık, net', 'clear'),
  adj('kompliziert', 'karmaşık', 'complicated'),
  adj('beliebt', 'sevilen, popüler', 'popular'),
  adj('erfolgreich', 'başarılı', 'successful'),
  adj('kostenlos', 'ücretsiz, bedava', 'free of charge'),

  // ── Quantity & degree ───────────────────────────────────────────────────────
  adj('zusätzlich', 'ek, ilave', 'additional'),
  adj('einzeln', 'tek tek, ayrı', 'individual'),
  adj('gesamt', 'toplam, bütün', 'entire, total'),
  adj('häufig', 'sık, sık görülen', 'frequent'),
  adj('vollständig', 'eksiksiz, tam', 'complete'),
  adj('halb', 'yarım', 'half'),
  adj('letzte', 'son, sonuncu', 'last'),
  adj('nächste', 'sonraki, en yakın', 'next'),
  adj('weitere', 'daha fazla, başka', 'further'),
  adj('einzige', 'tek, biricik', 'only, sole'),

  // ── Physical & sensory ──────────────────────────────────────────────────────
  adj('niedrig', 'alçak, düşük', 'low'),
  adj('schmal', 'dar, ince', 'narrow'),
  adj('riesig', 'devasa, kocaman', 'huge'),
  adj('winzig', 'minik, ufacık', 'tiny'),
  adj('bequem', 'rahat, konforlu', 'comfortable'),
  adj('unbequem', 'rahatsız', 'uncomfortable'),
  adj('feucht', 'nemli', 'damp'),
  adj('staubig', 'tozlu', 'dusty'),
  adj('durchsichtig', 'şeffaf', 'transparent'),
  adj('eiskalt', 'buz gibi', 'ice-cold'),
  adj('lauwarm', 'ılık', 'lukewarm'),
  adj('reif', 'olgun', 'ripe, mature'),
  adj('roh', 'çiğ', 'raw'),
  adj('giftig', 'zehirli', 'poisonous'),

  // ── Time & order ────────────────────────────────────────────────────────────
  adj('dringend', 'acil', 'urgent'),
  adj('endgültig', 'kesin, nihai', 'final'),
  adj('vorläufig', 'geçici', 'provisional'),
  adj('aktuell', 'güncel', 'current'),
  adj('damalig', 'o zamanki', 'then, of that time'),
  adj('künftig', 'gelecekteki', 'future'),
  adj('regelmäßig', 'düzenli', 'regular'),
  adj('unregelmäßig', 'düzensiz', 'irregular'),
  adj('vorherig', 'önceki', 'previous'),

  // ── Evaluation & quality ────────────────────────────────────────────────────
  adj('ausgezeichnet', 'mükemmel', 'excellent'),
  adj('hervorragend', 'olağanüstü, üstün', 'outstanding'),
  adj('großartig', 'harika', 'great'),
  adj('wunderbar', 'muhteşem', 'wonderful'),
  adj('schrecklich', 'korkunç', 'terrible'),
  adj('furchtbar', 'berbat', 'awful'),
  adj('angenehm', 'hoş, keyifli', 'pleasant'),
  adj('unangenehm', 'tatsız, nahoş', 'unpleasant'),
  adj('peinlich', 'utanç verici', 'embarrassing'),
  adj('perfekt', 'kusursuz', 'perfect'),
  adj('gewöhnlich', 'sıradan, alelade', 'ordinary'),
  adj('typisch', 'tipik', 'typical'),
  adj('passend', 'uygun, yerinde', 'suitable'),
  adj('geeignet', 'elverişli, uygun', 'appropriate'),
  adj('unfair', 'haksız, adaletsiz', 'unfair'),
  adj('gerecht', 'adil', 'just, fair'),
  adj('gründlich', 'titiz, etraflı', 'thorough'),
  adj('genau', 'tam, kesin', 'exact'),
  adj('ungenau', 'belirsiz, kabataslak', 'inaccurate'),

  // ── State & condition ───────────────────────────────────────────────────────
  adj('lebendig', 'canlı', 'alive, lively'),
  adj('tot', 'ölü', 'dead'),
  adj('verheiratet', 'evli', 'married'),
  adj('ledig', 'bekâr', 'single'),
  adj('schwanger', 'hamile', 'pregnant'),
  adj('arbeitslos', 'işsiz', 'unemployed'),
  adj('berufstätig', 'çalışan', 'employed'),
  adj('anwesend', 'mevcut, hazır bulunan', 'present'),
  adj('abwesend', 'yok, gelmemiş', 'absent'),
  adj('geöffnet', 'açık (dükkân)', 'open'),
  adj('geschlossen', 'kapalı', 'closed'),
  adj('kaputt', 'bozuk, kırık', 'broken'),
  adj('verfügbar', 'mevcut, ulaşılabilir', 'available'),
  adj('besetzt', 'dolu, meşgul', 'occupied'),
  adj('bereit', 'hazır', 'ready'),
  adj('verloren', 'kayıp', 'lost'),
  adj('gesperrt', 'kapalı, engellenmiş', 'blocked'),

  // ── Relations & abstract ────────────────────────────────────────────────────
  adj('öffentlich', 'kamuya açık, resmî', 'public'),
  adj('privat', 'özel, kişisel', 'private'),
  adj('persönlich', 'kişisel', 'personal'),
  adj('gemeinsam', 'ortak', 'common, joint'),
  adj('allgemein', 'genel', 'general'),
  adj('international', 'uluslararası', 'international'),
  adj('national', 'ulusal', 'national'),
  adj('politisch', 'siyasi', 'political'),
  adj('religiös', 'dinî', 'religious'),
  adj('sozial', 'sosyal, toplumsal', 'social'),
  adj('finanziell', 'mali, parasal', 'financial'),
  adj('gesetzlich', 'yasal', 'legal'),
  adj('illegal', 'yasa dışı', 'illegal'),
  adj('notwendig', 'gerekli, zorunlu', 'necessary'),
  adj('freiwillig', 'gönüllü', 'voluntary'),
  adj('verantwortlich', 'sorumlu', 'responsible'),
  adj('schuldig', 'suçlu; borçlu', 'guilty'),
  adj('unschuldig', 'masum', 'innocent'),
  adj('wahrscheinlich', 'muhtemel', 'probable'),

  // ── Colours ─────────────────────────────────────────────────────────────────
  adj('rot', 'kırmızı', 'red'),
  adj('blau', 'mavi', 'blue'),
  adj('grün', 'yeşil', 'green'),
  adj('gelb', 'sarı', 'yellow'),
  adj('schwarz', 'siyah', 'black'),
  adj('weiß', 'beyaz', 'white'),
  adj('grau', 'gri', 'grey'),
  adj('braun', 'kahverengi', 'brown'),
  adj('rosa', 'pembe', 'pink'),
  adj('orange', 'turuncu', 'orange'),
  adj('lila', 'mor', 'purple'),
  adj('golden', 'altın rengi', 'golden'),
  adj('silbern', 'gümüş rengi', 'silver'),
  adj('beige', 'bej', 'beige'),
  adj('hellblau', 'açık mavi', 'light blue'),
  adj('dunkelgrün', 'koyu yeşil', 'dark green'),

  // ── Texture & material ──────────────────────────────────────────────────────
  adj('hölzern', 'ahşap', 'wooden'),
  adj('metallisch', 'metalik', 'metallic'),
  adj('flüssig', 'sıvı', 'liquid'),
  adj('fest', 'katı, sağlam', 'solid, firm'),
  adj('klebrig', 'yapışkan', 'sticky'),
  adj('schlüpfrig', 'kaygan', 'slippery'),
  adj('haarig', 'tüylü', 'hairy'),
  adj('faltig', 'kırışık', 'wrinkled'),
  adj('zerknittert', 'buruşuk', 'crumpled'),
  adj('staubfrei', 'tozsuz', 'dust-free'),
  adj('schimmlig', 'küflü', 'mouldy'),
  adj('verrostet', 'paslı', 'rusty'),
  adj('matt', 'mat', 'matte'),
  adj('glänzend', 'parlak', 'shiny'),

  // ── Taste & condition of food ───────────────────────────────────────────────
  adj('würzig', 'baharatlı', 'spicy, savoury'),
  adj('salzig', 'tuzlu', 'salty'),
  adj('fettig', 'yağlı', 'greasy'),
  adj('mild', 'hafif, yumuşak', 'mild'),
  adj('knusprig', 'çıtır', 'crispy'),
  adj('zäh', 'sert, çiğnenmesi zor', 'tough, chewy'),
  adj('saftig', 'sulu, etli', 'juicy'),
  adj('verdorben', 'bozulmuş', 'spoiled'),
  adj('ungesund', 'sağlıksız', 'unhealthy'),
  adj('nahrhaft', 'besleyici', 'nutritious'),

  // ── Size & shape ────────────────────────────────────────────────────────────
  adj('gewaltig', 'muazzam, devasa', 'enormous'),
  adj('mächtig', 'güçlü, heybetli', 'mighty'),
  adj('massiv', 'masif, som', 'massive, solid'),
  adj('zierlich', 'narin, ince yapılı', 'dainty'),
  adj('oval', 'oval', 'oval'),
  adj('quadratisch', 'kare şeklinde', 'square'),
  adj('waagerecht', 'yatay', 'horizontal'),
  adj('senkrecht', 'dikey', 'vertical'),
  adj('krumm', 'eğri, çarpık', 'crooked'),
  adj('steil', 'dik, sarp', 'steep'),
  adj('schief', 'eğri, yamuk', 'slanted'),
  adj('hohl', 'içi boş', 'hollow'),
  adj('spitzig', 'sivri uçlu', 'pointy'),

  // ── Weather & environment ───────────────────────────────────────────────────
  adj('sonnig', 'güneşli', 'sunny'),
  adj('wolkig', 'bulutlu', 'cloudy'),
  adj('bewölkt', 'kapalı (hava)', 'overcast'),
  adj('regnerisch', 'yağışlı', 'rainy'),
  adj('windig', 'rüzgârlı', 'windy'),
  adj('neblig', 'sisli', 'foggy'),
  adj('stürmisch', 'fırtınalı', 'stormy'),
  adj('frostig', 'ayazlı, çok soğuk', 'frosty'),
  adj('schwül', 'bunaltıcı, boğucu', 'humid, muggy'),
  adj('heiter', 'açık, güneşli (hava); neşeli', 'bright, cheerful'),

  // ── Character & social (more) ───────────────────────────────────────────────
  adj('liebenswürdig', 'sevimli, hoş', 'amiable'),
  adj('grausam', 'zalim, acımasız', 'cruel'),
  adj('gemein', 'kötü, aşağılık', 'mean'),
  adj('frech', 'arsız, küstah', 'cheeky'),
  adj('boshaft', 'kötü niyetli', 'malicious'),
  adj('treu', 'sadık', 'loyal'),
  adj('ehrgeizig', 'hırslı, gözü yüksekte', 'ambitious'),
  adj('bescheiden', 'mütevazı', 'modest'),
  adj('arrogant', 'kibirli', 'arrogant'),
  adj('humorvoll', 'esprili', 'humorous'),
  adj('ernsthaft', 'ciddi', 'serious'),
  adj('vernünftig', 'mantıklı, makul', 'sensible'),
  adj('weise', 'bilge', 'wise'),
  adj('naiv', 'saf, toy', 'naive'),
  adj('aufmerksam', 'dikkatli, ilgili', 'attentive'),
  adj('rücksichtsvoll', 'düşünceli, saygılı', 'considerate'),
  adj('rücksichtslos', 'düşüncesiz, saygısız', 'reckless'),
  adj('tolerant', 'hoşgörülü', 'tolerant'),
  adj('sympathisch', 'sevimli, cana yakın', 'likeable'),
  adj('unsympathisch', 'itici, sevimsiz', 'unpleasant'),

  // ── State & feeling (more) ──────────────────────────────────────────────────
  adj('kerngesund', 'turp gibi sağlıklı', 'perfectly healthy'),
  adj('schläfrig', 'uykulu', 'sleepy'),
  adj('hellwach', 'tamamen uyanık', 'wide awake'),
  adj('gierig', 'açgözlü', 'greedy'),
  adj('genügsam', 'kanaatkâr, az ile yetinen', 'easily satisfied'),
  adj('verzweifelt', 'çaresiz, umutsuz', 'desperate'),
  adj('hoffnungsvoll', 'umut dolu', 'hopeful'),
  adj('eifrig', 'gayretli, istekli', 'keen'),
  adj('träge', 'uyuşuk, hantal', 'sluggish'),
  adj('begeistert', 'coşkulu, hayran', 'enthusiastic'),
  adj('gerührt', 'duygulanmış', 'moved, touched'),
  adj('schockiert', 'şok olmuş', 'shocked'),
  adj('beleidigt', 'gücenmiş, alınmış', 'offended'),
  adj('erleichtert', 'rahatlamış', 'relieved'),
  adj('gestresst', 'stresli', 'stressed'),
  adj('neidisch', 'kıskanç, gıpta eden', 'envious'),
  adj('verlegen', 'mahcup, utanmış', 'embarrassed'),
  adj('misstrauisch', 'kuşkucu, güvensiz', 'suspicious'),

  // ── Judgement & value (more) ────────────────────────────────────────────────
  adj('preiswert', 'uygun fiyatlı, hesaplı', 'good value'),
  adj('wertlos', 'değersiz', 'worthless'),
  adj('kostbar', 'kıymetli', 'precious'),
  adj('einzigartig', 'eşsiz, benzersiz', 'unique'),
  adj('durchschnittlich', 'ortalama', 'average'),
  adj('mittelmäßig', 'vasat', 'mediocre'),
  adj('erstklassig', 'birinci sınıf, üstün nitelikli', 'first-class'),
  adj('zufriedenstellend', 'tatmin edici', 'satisfactory'),
  adj('mangelhaft', 'yetersiz, kusurlu', 'deficient'),
  adj('wirksam', 'etkili', 'effective'),
  adj('sinnvoll', 'anlamlı, mantıklı', 'meaningful'),
  adj('sinnlos', 'anlamsız', 'pointless'),
  adj('vorteilhaft', 'avantajlı', 'advantageous'),
  adj('schädlich', 'zararlı', 'harmful'),
  adj('harmlos', 'zararsız', 'harmless'),
  adj('riskant', 'riskli', 'risky'),
  adj('geborgen', 'güven içinde, korunaklı', 'safe, secure'),
  adj('vertrauenswürdig', 'güvene layık', 'trustworthy'),

  // ── Difficulty & ability ────────────────────────────────────────────────────
  adj('machbar', 'yapılabilir', 'feasible'),
  adj('unlösbar', 'çözülemez', 'unsolvable'),
  adj('verständlich', 'anlaşılır', 'understandable'),
  adj('unverständlich', 'anlaşılmaz', 'incomprehensible'),
  adj('lesbar', 'okunaklı', 'legible'),
  adj('anstrengend', 'yorucu', 'strenuous'),
  adj('mühsam', 'zahmetli', 'laborious'),
  adj('herausfordernd', 'zorlayıcı', 'challenging'),
  adj('lernfähig', 'öğrenmeye yatkın', 'able to learn'),
  adj('fähig', 'yetenekli, ehil', 'capable'),
  adj('routiniert', 'işinin ehli, deneyimli', 'experienced, practised'),
  adj('unerfahren', 'deneyimsiz', 'inexperienced'),
  adj('geschickt', 'becerikli, mahir', 'skilful'),
  adj('ungeschickt', 'beceriksiz, sakar', 'clumsy'),

  // ── Position & relation ─────────────────────────────────────────────────────
  adj('nördlich', 'kuzey', 'northern'),
  adj('südlich', 'güney', 'southern'),
  adj('östlich', 'doğu', 'eastern'),
  adj('westlich', 'batı', 'western'),
  adj('städtisch', 'kentsel', 'urban'),
  adj('ländlich', 'kırsal', 'rural'),
  adj('benachbart', 'komşu, bitişik', 'neighbouring'),
  adj('entfernt', 'uzak', 'distant'),
  adj('zentral', 'merkezi', 'central'),
  adj('örtlich', 'yerel', 'local'),
  adj('weltweit', 'dünya çapında', 'worldwide'),
  adj('gegenseitig', 'karşılıklı', 'mutual'),
];
