// Extended German verb bank — batch 3 of the curated expansion (~690 → ~2000).
// Common A2-level verbs with hand-checked Turkish meanings and example
// sentences. Conjugation tables are produced by getGermanConjugation().
import type { CuratedWord } from '@/lib/mock-data';

const v = (word: string, tr: string, en: string, exDe: string, exTr: string): CuratedWord => ({
  id: word,
  word,
  language: 'de',
  type: 'verb',
  shortDef: { tr, en },
  example: { text: exDe, translation: exTr },
});

export const GERMAN_VERBS_EXTRA: CuratedWord[] = [
  // ── Everyday actions ────────────────────────────────────────────────────────
  v('aufstehen', 'kalkmak, ayağa kalkmak', 'to get up', 'Ich stehe um sieben Uhr auf.', 'Saat yedide kalkıyorum.'),
  v('aufwachen', 'uyanmak', 'to wake up', 'Ich wache früh auf.', 'Erken uyanırım.'),
  v('einschlafen', 'uykuya dalmak', 'to fall asleep', 'Das Kind schläft schnell ein.', 'Çocuk hızlıca uykuya dalıyor.'),
  v('anziehen', 'giyinmek, giymek', 'to put on (clothes)', 'Zieh deine Jacke an.', 'Ceketini giy.'),
  v('ausziehen', 'çıkarmak (giysi); taşınmak', 'to take off; to move out', 'Ich ziehe die Schuhe aus.', 'Ayakkabılarımı çıkarıyorum.'),
  v('duschen', 'duş almak', 'to shower', 'Ich dusche jeden Morgen.', 'Her sabah duş alıyorum.'),
  v('waschen', 'yıkamak', 'to wash', 'Wasch deine Hände.', 'Ellerini yıka.'),
  v('aufräumen', 'toplamak, derleyip toparlamak', 'to tidy up', 'Räum dein Zimmer auf.', 'Odanı topla.'),
  v('frühstücken', 'kahvaltı yapmak', 'to have breakfast', 'Wir frühstücken zusammen.', 'Birlikte kahvaltı yapıyoruz.'),
  v('vorbereiten', 'hazırlamak', 'to prepare', 'Ich bereite das Essen vor.', 'Yemeği hazırlıyorum.'),
  v('reparieren', 'tamir etmek', 'to repair', 'Er repariert das Fahrrad.', 'Bisikleti tamir ediyor.'),
  v('mitnehmen', 'yanına almak', 'to take along', 'Nimm einen Regenschirm mit.', 'Yanına şemsiye al.'),
  v('abholen', 'almaya gitmek, teslim almak', 'to pick up', 'Ich hole dich vom Bahnhof ab.', 'Seni istasyondan alacağım.'),
  v('einkaufen', 'alışveriş yapmak', 'to go shopping', 'Wir kaufen am Samstag ein.', 'Cumartesi alışveriş yapıyoruz.'),

  // ── Communication ───────────────────────────────────────────────────────────
  v('sprechen', 'konuşmak', 'to speak', 'Sie spricht drei Sprachen.', 'O üç dil konuşuyor.'),
  v('reden', 'konuşmak, laflamak', 'to talk', 'Wir reden über das Wetter.', 'Hava durumu hakkında konuşuyoruz.'),
  v('rufen', 'çağırmak, seslenmek', 'to call', 'Er ruft seinen Hund.', 'Köpeğini çağırıyor.'),
  v('anrufen', 'telefonla aramak', 'to phone', 'Ich rufe dich später an.', 'Seni sonra ararım.'),
  v('wiederholen', 'tekrarlamak', 'to repeat', 'Wiederhole den Satz.', 'Cümleyi tekrarla.'),
  v('buchstabieren', 'harf harf söylemek', 'to spell', 'Buchstabiere deinen Namen.', 'Adını harf harf söyle.'),
  v('übersetzen', 'çevirmek', 'to translate', 'Ich übersetze den Text.', 'Metni çeviriyorum.'),
  v('bedeuten', 'anlamına gelmek', 'to mean', 'Was bedeutet dieses Wort?', 'Bu kelime ne anlama geliyor?'),
  v('versprechen', 'söz vermek', 'to promise', 'Ich verspreche es dir.', 'Sana söz veriyorum.'),
  v('vorstellen', 'tanıtmak; hayal etmek', 'to introduce; to imagine', 'Darf ich dir meinen Freund vorstellen?', 'Sana arkadaşımı tanıtabilir miyim?'),
  v('bitten', 'rica etmek', 'to ask for', 'Ich bitte um Hilfe.', 'Yardım rica ediyorum.'),
  v('grüßen', 'selam vermek', 'to greet', 'Grüß deine Familie.', 'Ailene selam söyle.'),

  // ── Thinking & learning ─────────────────────────────────────────────────────
  v('lernen', 'öğrenmek', 'to learn', 'Ich lerne Deutsch.', 'Almanca öğreniyorum.'),
  v('verstehen', 'anlamak', 'to understand', 'Ich verstehe dich nicht.', 'Seni anlamıyorum.'),
  v('vergessen', 'unutmak', 'to forget', 'Vergiss deinen Schlüssel nicht.', 'Anahtarını unutma.'),
  v('erinnern', 'hatırlamak, anımsamak', 'to remember', 'Ich erinnere mich an dich.', 'Seni hatırlıyorum.'),
  v('merken', 'fark etmek; aklında tutmak', 'to notice', 'Ich merke den Unterschied.', 'Farkı fark ediyorum.'),
  v('entscheiden', 'karar vermek', 'to decide', 'Du musst dich entscheiden.', 'Karar vermelisin.'),
  v('überlegen', 'düşünüp taşınmak', 'to consider', 'Ich überlege es mir.', 'Bunu düşüneceğim.'),
  v('lesen', 'okumak', 'to read', 'Ich lese ein Buch.', 'Bir kitap okuyorum.'),
  v('schreiben', 'yazmak', 'to write', 'Sie schreibt einen Brief.', 'O bir mektup yazıyor.'),
  v('rechnen', 'hesaplamak', 'to calculate', 'Kinder lernen rechnen.', 'Çocuklar hesap yapmayı öğrenir.'),
  v('zählen', 'saymak', 'to count', 'Zähl bis zehn.', 'Ona kadar say.'),
  v('raten', 'tahmin etmek; öğüt vermek', 'to guess; to advise', 'Rate mal!', 'Tahmin et bakalım!'),
  v('prüfen', 'kontrol etmek, sınamak', 'to check', 'Der Lehrer prüft die Aufgaben.', 'Öğretmen ödevleri kontrol ediyor.'),
  v('kennen', 'tanımak, bilmek', 'to know (be familiar)', 'Ich kenne diese Stadt.', 'Bu şehri tanıyorum.'),
  v('kennenlernen', 'tanışmak', 'to get to know', 'Ich möchte dich kennenlernen.', 'Seninle tanışmak istiyorum.'),

  // ── Movement & travel ───────────────────────────────────────────────────────
  v('gehen', 'gitmek, yürümek', 'to go', 'Ich gehe zur Schule.', 'Okula gidiyorum.'),
  v('reisen', 'seyahat etmek', 'to travel', 'Wir reisen nach Italien.', 'İtalya\'ya seyahat ediyoruz.'),
  v('ankommen', 'varmak, ulaşmak', 'to arrive', 'Der Zug kommt pünktlich an.', 'Tren zamanında varıyor.'),
  v('abfahren', 'hareket etmek, kalkmak', 'to depart', 'Der Bus fährt um acht ab.', 'Otobüs sekizde kalkıyor.'),
  v('einsteigen', 'binmek (araca)', 'to get in/on', 'Steig bitte ein.', 'Lütfen bin.'),
  v('aussteigen', 'inmek (araçtan)', 'to get off', 'Wir steigen hier aus.', 'Burada iniyoruz.'),
  v('umsteigen', 'aktarma yapmak', 'to change (transport)', 'Du musst in Köln umsteigen.', 'Köln\'de aktarma yapmalısın.'),
  v('mitkommen', 'birlikte gelmek', 'to come along', 'Kommst du mit?', 'Bizimle gelir misin?'),
  v('zurückkommen', 'geri gelmek', 'to come back', 'Ich komme bald zurück.', 'Yakında geri geleceğim.'),
  v('weggehen', 'gitmek, ayrılmak', 'to leave, to go away', 'Bitte geh nicht weg.', 'Lütfen gitme.'),
  v('folgen', 'takip etmek, izlemek', 'to follow', 'Folge mir.', 'Beni takip et.'),
  v('begegnen', 'rastlaşmak, karşılaşmak', 'to encounter', 'Ich begegne ihm oft.', 'Ona sık rastlarım.'),
  v('springen', 'zıplamak, atlamak', 'to jump', 'Der Hund springt hoch.', 'Köpek yükseğe zıplıyor.'),
  v('klettern', 'tırmanmak', 'to climb', 'Die Kinder klettern auf den Baum.', 'Çocuklar ağaca tırmanıyor.'),
  v('schwimmen', 'yüzmek', 'to swim', 'Wir schwimmen im See.', 'Gölde yüzüyoruz.'),

  // ── Work & daily life ───────────────────────────────────────────────────────
  v('verdienen', 'kazanmak (para)', 'to earn', 'Sie verdient gut.', 'O iyi kazanıyor.'),
  v('bezahlen', 'ödemek', 'to pay', 'Ich bezahle die Rechnung.', 'Hesabı ödüyorum.'),
  v('verkaufen', 'satmak', 'to sell', 'Er verkauft sein Auto.', 'Arabasını satıyor.'),
  v('bestellen', 'sipariş vermek', 'to order', 'Wir bestellen eine Pizza.', 'Bir pizza sipariş ediyoruz.'),
  v('mieten', 'kiralamak', 'to rent', 'Sie mietet eine Wohnung.', 'O bir daire kiralıyor.'),
  v('sparen', 'biriktirmek, tasarruf etmek', 'to save (money)', 'Ich spare für ein Auto.', 'Araba için para biriktiriyorum.'),
  v('anfangen', 'başlamak', 'to begin', 'Der Film fängt jetzt an.', 'Film şimdi başlıyor.'),
  v('beginnen', 'başlamak', 'to begin', 'Wir beginnen um neun.', 'Dokuzda başlıyoruz.'),
  v('aufhören', 'son vermek, durdurmak', 'to stop', 'Hör auf zu reden.', 'Konuşmayı bırak.'),
  v('beenden', 'bitirmek', 'to finish', 'Ich beende die Arbeit.', 'İşi bitiriyorum.'),
  v('schaffen', 'başarmak, üstesinden gelmek', 'to manage', 'Wir schaffen das.', 'Bunu başarırız.'),
  v('versuchen', 'denemek, çalışmak', 'to try', 'Ich versuche es noch einmal.', 'Bir kez daha deniyorum.'),
  v('teilnehmen', 'katılmak', 'to participate', 'Sie nimmt am Kurs teil.', 'O kursa katılıyor.'),
  v('unterschreiben', 'imzalamak', 'to sign', 'Bitte unterschreiben Sie hier.', 'Lütfen burayı imzalayın.'),

  // ── Feelings & states ───────────────────────────────────────────────────────
  v('fühlen', 'hissetmek', 'to feel', 'Ich fühle mich gut.', 'Kendimi iyi hissediyorum.'),
  v('weinen', 'ağlamak', 'to cry', 'Das Baby weint.', 'Bebek ağlıyor.'),
  v('lächeln', 'gülümsemek', 'to smile', 'Sie lächelt freundlich.', 'O dostça gülümsüyor.'),
  v('freuen', 'sevinmek (sich freuen)', 'to be glad', 'Ich freue mich auf dich.', 'Seni görmeye sevineceğim.'),
  v('ärgern', 'kızmak, sinirlenmek (sich ärgern)', 'to be annoyed', 'Er ärgert sich oft.', 'O sık sinirlenir.'),
  v('fürchten', 'korkmak (sich fürchten)', 'to be afraid', 'Das Kind fürchtet sich vor dem Hund.', 'Çocuk köpekten korkuyor.'),
  v('hassen', 'nefret etmek', 'to hate', 'Ich hasse Lärm.', 'Gürültüden nefret ederim.'),
  v('mögen', 'hoşlanmak, sevmek', 'to like', 'Ich mag Kaffee.', 'Kahveyi severim.'),

  // ── Modal verbs (CRITICAL — bulk dict has bad chained translations) ─────────
  // Hand-checked from Menschen / Schritte textbook examples; never let live
  // translation override these. "dürfen" → "mayıs" is the canonical Google bug
  // we are correcting here.
  v('dürfen', 'izni olmak, -ebilmek (izin)', 'may, to be allowed to', 'Darf ich rein?', 'İçeri girebilir miyim?'),
  v('können', '-ebilmek (yetenek/imkân)', 'can, to be able to', 'Kannst du schwimmen?', 'Yüzebilir misin?'),
  v('müssen', 'zorunda olmak, -meli', 'must, to have to', 'Ich muss jetzt gehen.', 'Şimdi gitmek zorundayım.'),
  v('sollen', '-meli (öneri/yükümlülük)', 'should, ought to', 'Du sollst pünktlich sein.', 'Dakik olmalısın.'),
  v('wollen', 'istemek (kesin niyet)', 'to want (firmly)', 'Ich will Deutsch lernen.', 'Almanca öğrenmek istiyorum.'),
  v('möchten', 'istemek (kibarca, dilek)', 'would like to', 'Ich möchte einen Kaffee, bitte.', 'Lütfen bir kahve istiyorum.'),

  // ── Multi-meaning verbs — bulk dict gives one sense, real usage has many.
  //    lassen, heißen are covered in german-verbs.ts (base list); liegen and
  //    stehen are covered later in this file.
  v('führen', 'yönetmek; götürmek (yol)', 'to lead; (of a road) to go to', 'Diese Straße führt zum Markt.', 'Bu yol pazara çıkar.'),
  v('genießen', 'tadını çıkarmak', 'to enjoy', 'Wir genießen die Sonne.', 'Güneşin tadını çıkarıyoruz.'),
  v('entspannen', 'rahatlamak, dinlenmek (sich entspannen)', 'to relax', 'Ich entspanne mich am Wochenende.', 'Hafta sonu rahatlıyorum.'),
  v('beeilen', 'acele etmek (sich beeilen)', 'to hurry', 'Beeil dich!', 'Acele et!'),
  v('staunen', 'şaşırmak, hayret etmek', 'to be amazed', 'Die Kinder staunen über die Show.', 'Çocuklar gösteriye hayret ediyor.'),
  v('interessieren', 'ilgilenmek (sich interessieren)', 'to be interested', 'Ich interessiere mich für Musik.', 'Müzikle ilgileniyorum.'),

  // ── Change & creation ───────────────────────────────────────────────────────
  v('ändern', 'değiştirmek', 'to change', 'Ich ändere meinen Plan.', 'Planımı değiştiriyorum.'),
  v('wechseln', 'değiştirmek, takas etmek', 'to switch', 'Ich wechsle das Geld.', 'Parayı bozduruyorum.'),
  v('bauen', 'inşa etmek, yapmak', 'to build', 'Sie bauen ein Haus.', 'Bir ev inşa ediyorlar.'),
  v('schneiden', 'kesmek', 'to cut', 'Ich schneide das Brot.', 'Ekmeği kesiyorum.'),
  v('malen', 'resim yapmak', 'to paint', 'Das Kind malt ein Bild.', 'Çocuk bir resim yapıyor.'),
  v('zeichnen', 'çizmek', 'to draw', 'Er zeichnet ein Haus.', 'O bir ev çiziyor.'),
  v('backen', 'fırında pişirmek', 'to bake', 'Wir backen einen Kuchen.', 'Bir kek pişiriyoruz.'),
  v('wachsen', 'büyümek, yetişmek', 'to grow', 'Die Blume wächst schnell.', 'Çiçek hızlı büyüyor.'),
  v('verbessern', 'iyileştirmek, geliştirmek', 'to improve', 'Ich verbessere mein Deutsch.', 'Almancamı geliştiriyorum.'),
  v('entwickeln', 'geliştirmek', 'to develop', 'Sie entwickeln eine App.', 'Bir uygulama geliştiriyorlar.'),
  v('reinigen', 'temizlemek', 'to clean', 'Ich reinige den Teppich.', 'Halıyı temizliyorum.'),
  v('füllen', 'doldurmak', 'to fill', 'Füll das Glas mit Wasser.', 'Bardağı suyla doldur.'),
  v('leeren', 'boşaltmak', 'to empty', 'Ich leere den Mülleimer.', 'Çöp kovasını boşaltıyorum.'),
  v('drücken', 'basmak, itmek', 'to press, to push', 'Drück den Knopf.', 'Düğmeye bas.'),
  v('ziehen', 'çekmek', 'to pull', 'Zieh die Tür zu.', 'Kapıyı çek.'),

  // ── Perception & misc ───────────────────────────────────────────────────────
  v('schauen', 'bakmak', 'to look', 'Schau aus dem Fenster.', 'Pencereden bak.'),
  v('beobachten', 'gözlemlemek', 'to observe', 'Wir beobachten die Vögel.', 'Kuşları gözlemliyoruz.'),
  v('riechen', 'koku almak, kokmak', 'to smell', 'Die Blumen riechen gut.', 'Çiçekler güzel kokuyor.'),
  v('schmecken', 'tadı olmak, tatmak', 'to taste', 'Das Essen schmeckt gut.', 'Yemek güzel.'),
  v('berühren', 'dokunmak, ellemek', 'to touch', 'Bitte nicht berühren.', 'Lütfen dokunmayın.'),
  v('gehören', 'ait olmak', 'to belong', 'Das Buch gehört mir.', 'Kitap bana ait.'),
  v('passen', 'uymak, yakışmak', 'to fit, to suit', 'Die Hose passt mir.', 'Pantolon bana uyuyor.'),
  v('stören', 'rahatsız etmek', 'to disturb', 'Störe ich dich?', 'Seni rahatsız ediyor muyum?'),
  v('vermissen', 'özlemek', 'to miss', 'Ich vermisse dich.', 'Seni özlüyorum.'),

  // ── B1 — opinion & communication ────────────────────────────────────────────
  v('meinen', 'demek istemek, düşünmek', 'to mean, to think', 'Was meinst du damit?', 'Bununla ne demek istiyorsun?'),
  v('behaupten', 'iddia etmek', 'to claim', 'Er behauptet, er sei krank.', 'Hasta olduğunu iddia ediyor.'),
  v('zugeben', 'itiraf etmek, kabul etmek', 'to admit', 'Ich gebe meinen Fehler zu.', 'Hatamı kabul ediyorum.'),
  v('vorschlagen', 'önermek', 'to suggest', 'Ich schlage einen Spaziergang vor.', 'Bir yürüyüş öneriyorum.'),
  v('empfehlen', 'tavsiye etmek', 'to recommend', 'Ich empfehle dieses Buch.', 'Bu kitabı tavsiye ederim.'),
  v('beschreiben', 'tarif etmek, betimlemek', 'to describe', 'Beschreib mir das Haus.', 'Bana evi tarif et.'),
  v('streiten', 'tartışmak, kavga etmek', 'to argue', 'Sie streiten oft.', 'Sık kavga ederler.'),
  v('beschweren', 'şikâyet etmek (sich beschweren)', 'to complain', 'Er beschwert sich über den Lärm.', 'Gürültüden şikâyet ediyor.'),
  v('bedanken', 'teşekkür etmek (sich bedanken)', 'to thank', 'Ich bedanke mich bei dir.', 'Sana teşekkür ediyorum.'),
  v('entschuldigen', 'özür dilemek (sich entschuldigen)', 'to apologise', 'Ich entschuldige mich für die Verspätung.', 'Gecikme için özür dilerim.'),
  v('berichten', 'bildirmek, haber vermek', 'to report', 'Die Zeitung berichtet darüber.', 'Gazete bunu haber veriyor.'),
  v('erwähnen', 'bahsetmek, anmak', 'to mention', 'Sie erwähnte deinen Namen.', 'Senin adını andı.'),
  v('warnen', 'uyarmak', 'to warn', 'Ich warne dich.', 'Seni uyarıyorum.'),
  v('überzeugen', 'ikna etmek', 'to convince', 'Du hast mich überzeugt.', 'Beni ikna ettin.'),

  // ── B1 — thinking & planning ────────────────────────────────────────────────
  v('planen', 'planlamak', 'to plan', 'Wir planen eine Reise.', 'Bir gezi planlıyoruz.'),
  v('vergleichen', 'karşılaştırmak', 'to compare', 'Vergleich die zwei Preise.', 'İki fiyatı karşılaştır.'),
  v('verbinden', 'bağlamak, birleştirmek', 'to connect', 'Das verbindet die zwei Städte.', 'Bu iki şehri birbirine bağlar.'),
  v('unterscheiden', 'ayırt etmek', 'to distinguish', 'Ich kann sie nicht unterscheiden.', 'Onları ayırt edemiyorum.'),
  v('bemerken', 'fark etmek', 'to notice', 'Ich habe den Fehler bemerkt.', 'Hatayı fark ettim.'),
  v('erkennen', 'tanımak, fark etmek', 'to recognise', 'Ich erkenne dich kaum.', 'Seni zor tanıdım.'),
  v('beweisen', 'kanıtlamak', 'to prove', 'Kannst du das beweisen?', 'Bunu kanıtlayabilir misin?'),
  v('annehmen', 'varsaymak; kabul etmek', 'to assume, to accept', 'Ich nehme an, du kommst.', 'Geleceğini varsayıyorum.'),
  v('aufpassen', 'dikkat etmek', 'to pay attention', 'Pass auf den Verkehr auf!', 'Trafiğe dikkat et!'),
  v('beachten', 'dikkate almak, uymak', 'to observe, to heed', 'Beachte die Regeln.', 'Kurallara uy.'),
  v('zweifeln', 'şüphe etmek', 'to doubt', 'Ich zweifle daran.', 'Bundan şüphe ediyorum.'),
  v('schätzen', 'tahmin etmek; değer vermek', 'to estimate, to value', 'Ich schätze ihn sehr.', 'Ona çok değer veriyorum.'),
  v('wählen', 'seçmek; oy vermek', 'to choose, to vote', 'Wähl eine Farbe.', 'Bir renk seç.'),

  // ── B1 — actions & change ───────────────────────────────────────────────────
  v('erlauben', 'izin vermek', 'to allow', 'Meine Eltern erlauben es nicht.', 'Ailem buna izin vermiyor.'),
  v('verbieten', 'yasaklamak', 'to forbid', 'Rauchen ist hier verboten.', 'Burada sigara içmek yasaktır.'),
  v('verlangen', 'talep etmek, istemek', 'to demand', 'Sie verlangt eine Erklärung.', 'Bir açıklama istiyor.'),
  v('verzichten', 'vazgeçmek', 'to give up, to forgo', 'Ich verzichte auf Zucker.', 'Şekerden vazgeçiyorum.'),
  v('erreichen', 'ulaşmak, erişmek', 'to reach', 'Wir erreichen das Ziel.', 'Hedefe ulaşıyoruz.'),
  v('vermeiden', 'kaçınmak', 'to avoid', 'Vermeide Stress.', 'Stresten kaçın.'),
  v('verursachen', 'neden olmak', 'to cause', 'Der Regen verursacht Staus.', 'Yağmur trafik sıkışıklığına neden oluyor.'),
  v('ersetzen', 'değiştirmek, yerine koymak', 'to replace', 'Ich ersetze die Batterie.', 'Pili değiştiriyorum.'),
  v('verschieben', 'ertelemek', 'to postpone', 'Wir verschieben das Treffen.', 'Toplantıyı erteliyoruz.'),
  v('verbringen', 'geçirmek (zaman)', 'to spend (time)', 'Wir verbringen den Urlaub am Meer.', 'Tatili deniz kenarında geçiriyoruz.'),
  v('gewöhnen', 'alışmak (sich gewöhnen)', 'to get used to', 'Ich gewöhne mich an das Wetter.', 'Havaya alışıyorum.'),
  v('verändern', 'değiştirmek', 'to change, to alter', 'Die Stadt hat sich verändert.', 'Şehir değişti.'),
  v('retten', 'kurtarmak', 'to rescue', 'Er hat das Kind gerettet.', 'Çocuğu kurtardı.'),
  v('schützen', 'korumak', 'to protect', 'Wir schützen die Natur.', 'Doğayı koruyoruz.'),
  v('teilen', 'paylaşmak; bölmek', 'to share, to divide', 'Wir teilen die Pizza.', 'Pizzayı paylaşıyoruz.'),
  v('sammeln', 'toplamak, biriktirmek', 'to collect', 'Er sammelt Briefmarken.', 'Pul biriktiriyor.'),
  v('verstecken', 'saklamak, gizlemek', 'to hide', 'Das Kind versteckt sich.', 'Çocuk saklanıyor.'),
  v('werfen', 'atmak, fırlatmak', 'to throw', 'Wirf mir den Ball.', 'Bana topu at.'),
  v('fangen', 'yakalamak', 'to catch', 'Der Torwart fängt den Ball.', 'Kaleci topu yakalıyor.'),

  // ── B1 — work, study & society ──────────────────────────────────────────────
  v('bewerben', 'başvurmak (sich bewerben)', 'to apply', 'Ich bewerbe mich um die Stelle.', 'İş için başvuruyorum.'),
  v('kündigen', 'işten ayrılmak, fesih etmek', 'to resign, to cancel', 'Er hat seinen Job gekündigt.', 'İşinden ayrıldı.'),
  v('verhandeln', 'pazarlık yapmak, görüşmek', 'to negotiate', 'Wir verhandeln über den Preis.', 'Fiyat üzerine pazarlık ediyoruz.'),
  v('unterstützen', 'desteklemek', 'to support', 'Meine Familie unterstützt mich.', 'Ailem beni destekliyor.'),
  v('verwalten', 'yönetmek', 'to manage, to administer', 'Sie verwaltet das Geld.', 'Parayı o yönetiyor.'),
  v('leiten', 'yönetmek, idare etmek', 'to lead', 'Er leitet die Firma.', 'Şirketi o yönetiyor.'),
  v('gründen', 'kurmak', 'to found', 'Sie gründen eine Firma.', 'Bir şirket kuruyorlar.'),
  v('bestehen', 'geçmek (sınav); var olmak', 'to pass; to exist', 'Ich habe die Prüfung bestanden.', 'Sınavı geçtim.'),
  v('scheitern', 'başarısız olmak', 'to fail', 'Der Plan ist gescheitert.', 'Plan başarısız oldu.'),
  v('konzentrieren', 'odaklanmak (sich konzentrieren)', 'to concentrate', 'Ich konzentriere mich auf die Arbeit.', 'İşe odaklanıyorum.'),
  v('vertrauen', 'güvenmek', 'to trust', 'Ich vertraue dir.', 'Sana güveniyorum.'),
  v('verwenden', 'kullanmak', 'to use', 'Verwende ein neues Wort.', 'Yeni bir kelime kullan.'),
  v('erfahren', 'öğrenmek, haberdar olmak', 'to find out', 'Ich habe es gestern erfahren.', 'Bunu dün öğrendim.'),
  v('mitteilen', 'bildirmek', 'to inform', 'Teilen Sie uns Ihre Adresse mit.', 'Adresinizi bize bildirin.'),

  // ── B1 — daily situations ───────────────────────────────────────────────────
  v('einladen', 'davet etmek', 'to invite', 'Ich lade dich zum Essen ein.', 'Seni yemeğe davet ediyorum.'),
  v('absagen', 'iptal etmek', 'to cancel', 'Ich muss den Termin absagen.', 'Randevuyu iptal etmem gerek.'),
  v('vereinbaren', 'kararlaştırmak', 'to arrange', 'Wir vereinbaren einen Termin.', 'Bir randevu kararlaştırıyoruz.'),
  v('verabreden', 'sözleşmek, buluşmak için anlaşmak', 'to arrange to meet', 'Wir haben uns für Montag verabredet.', 'Pazartesi için sözleştik.'),
  v('umziehen', 'taşınmak', 'to move house', 'Wir ziehen nächsten Monat um.', 'Gelecek ay taşınıyoruz.'),
  v('aufwachsen', 'büyümek (yetişmek)', 'to grow up', 'Ich bin in Berlin aufgewachsen.', 'Berlin\'de büyüdüm.'),
  v('heiraten', 'evlenmek', 'to marry', 'Sie heiraten im Sommer.', 'Yazın evleniyorlar.'),
  v('verabschieden', 'vedalaşmak (sich verabschieden)', 'to say goodbye', 'Wir verabschieden uns am Bahnhof.', 'İstasyonda vedalaşıyoruz.'),
  v('klingeln', 'zil çalmak', 'to ring', 'Es klingelt an der Tür.', 'Kapı zili çalıyor.'),
  v('atmen', 'nefes almak', 'to breathe', 'Atme tief ein.', 'Derin nefes al.'),
  v('verletzen', 'yaralamak, incitmek', 'to injure, to hurt', 'Ich habe mich am Knie verletzt.', 'Dizimi yaraladım.'),
  v('heilen', 'iyileştirmek, iyileşmek', 'to heal', 'Die Wunde heilt schnell.', 'Yara hızlı iyileşiyor.'),
  v('wehtun', 'acımak, ağrımak', 'to hurt', 'Mein Kopf tut weh.', 'Başım ağrıyor.'),
  v('erholen', 'iyileşmek, dinlenmek (sich erholen)', 'to recover', 'Er erholt sich von der Krankheit.', 'Hastalıktan iyileşiyor.'),

  // ── More everyday & B1 verbs ────────────────────────────────────────────────
  v('aufmachen', 'açmak', 'to open', 'Mach das Fenster auf.', 'Pencereyi aç.'),
  v('zumachen', 'kapatmak', 'to close', 'Mach die Tür zu.', 'Kapıyı kapat.'),
  v('anmachen', 'açmak (cihaz)', 'to turn on', 'Mach das Licht an.', 'Işığı aç.'),
  v('ausmachen', 'kapatmak (cihaz); önemi olmak', 'to turn off', 'Mach den Fernseher aus.', 'Televizyonu kapat.'),
  v('anschauen', 'bakmak, izlemek', 'to look at', 'Schau dir das Bild an.', 'Resme bak.'),
  v('ansehen', 'seyretmek, bakmak', 'to watch', 'Wir sehen uns einen Film an.', 'Bir film izliyoruz.'),
  v('zuhören', 'dinlemek', 'to listen', 'Hör mir bitte zu.', 'Lütfen beni dinle.'),
  v('aufschreiben', 'not almak, yazmak', 'to write down', 'Schreib die Adresse auf.', 'Adresi yaz.'),
  v('ausfüllen', 'doldurmak (form)', 'to fill in', 'Füll das Formular aus.', 'Formu doldur.'),
  v('unterstreichen', 'altını çizmek', 'to underline', 'Unterstreich das wichtige Wort.', 'Önemli kelimenin altını çiz.'),
  v('ausdrücken', 'ifade etmek', 'to express', 'Ich kann es nicht gut ausdrücken.', 'Bunu iyi ifade edemiyorum.'),
  v('aufnehmen', 'kaydetmek; içine almak', 'to record; to take in', 'Ich nehme das Gespräch auf.', 'Konuşmayı kaydediyorum.'),
  v('mitbringen', 'beraberinde getirmek', 'to bring along', 'Bring etwas zu essen mit.', 'Yiyecek bir şey getir.'),
  v('weitermachen', 'devam etmek', 'to carry on', 'Mach bitte weiter.', 'Lütfen devam et.'),
  v('aufgeben', 'pes etmek; (görev) vermek', 'to give up', 'Gib niemals auf.', 'Asla pes etme.'),
  v('nachdenken', 'derin düşünmek', 'to think about', 'Ich denke über das Angebot nach.', 'Teklifi düşünüyorum.'),
  v('herstellen', 'üretmek', 'to produce', 'Die Fabrik stellt Autos her.', 'Fabrika araba üretiyor.'),
  v('verbrauchen', 'tüketmek', 'to consume', 'Das Auto verbraucht viel Benzin.', 'Araba çok benzin tüketiyor.'),
  v('mitmachen', 'katılmak, iştirak etmek', 'to join in', 'Machst du beim Spiel mit?', 'Oyuna katılır mısın?'),
  v('zusammenarbeiten', 'birlikte çalışmak', 'to cooperate', 'Wir arbeiten gut zusammen.', 'İyi birlikte çalışıyoruz.'),
  v('kümmern', 'ilgilenmek, bakmak (sich kümmern)', 'to take care of', 'Ich kümmere mich um die Kinder.', 'Çocuklarla ben ilgileniyorum.'),
  v('verlassen', 'terk etmek, ayrılmak', 'to leave', 'Er verlässt das Haus früh.', 'Evden erken ayrılıyor.'),
  v('betreten', 'içine girmek', 'to enter', 'Betreten Sie den Raum leise.', 'Odaya sessizce girin.'),
  v('verlaufen', 'gelişmek, seyretmek', 'to go, to proceed', 'Alles verläuft gut.', 'Her şey yolunda gidiyor.'),
  v('gelingen', 'başarılı olmak, becermek', 'to succeed', 'Der Kuchen ist mir gelungen.', 'Kek güzel oldu.'),
  v('lohnen', 'değmek, kârlı olmak (sich lohnen)', 'to be worth it', 'Die Reise lohnt sich.', 'Yolculuk buna değer.'),
  v('aussehen', 'görünmek', 'to look, to appear', 'Du siehst müde aus.', 'Yorgun görünüyorsun.'),
  v('scheinen', 'görünmek; (güneş) parlamak', 'to seem; to shine', 'Die Sonne scheint.', 'Güneş parlıyor.'),
  v('klingen', 'kulağa gelmek', 'to sound', 'Das klingt gut.', 'Kulağa hoş geliyor.'),
  v('wirken', 'etki etmek; izlenim vermek', 'to have an effect', 'Das Medikament wirkt schnell.', 'İlaç hızlı etki ediyor.'),
  v('befinden', 'bulunmak, konumlanmak (sich befinden)', 'to be located', 'Das Hotel befindet sich im Zentrum.', 'Otel merkezde bulunuyor.'),
  v('liegen', 'yatmak; (bir yerde) bulunmak, durmak', 'to lie; to be located', 'Das Buch liegt auf dem Tisch.', 'Kitap masanın üstünde.'),
  v('stehen', 'ayakta durmak; (bir yerde) bulunmak; (yazıda) yazmak', 'to stand; to be situated; to be written', 'Wir stehen vor dem Haus.', 'Evin önünde duruyoruz.'),
  v('sitzen', 'oturmak', 'to sit', 'Sie sitzt am Fenster.', 'O pencerenin yanında oturuyor.'),
  v('hängen', 'asılı olmak, asmak', 'to hang', 'Das Bild hängt an der Wand.', 'Resim duvarda asılı.'),
  v('stecken', 'sokmak; (bir yerde) olmak', 'to stick, to put', 'Steck den Schlüssel in die Tasche.', 'Anahtarı cebine koy.'),
  v('greifen', 'tutmak, kavramak', 'to grab', 'Er greift nach dem Buch.', 'Kitaba uzanıyor.'),
  v('schieben', 'itmek', 'to push', 'Schieb den Tisch zur Wand.', 'Masayı duvara doğru it.'),
  v('heben', 'kaldırmak', 'to lift', 'Heb die Kiste vorsichtig.', 'Kutuyu dikkatlice kaldır.'),
  v('drehen', 'döndürmek', 'to turn', 'Dreh den Schlüssel nach rechts.', 'Anahtarı sağa çevir.'),
  v('fließen', 'akmak', 'to flow', 'Der Fluss fließt zum Meer.', 'Nehir denize akıyor.'),
  v('brennen', 'yanmak', 'to burn', 'Das Feuer brennt hell.', 'Ateş parlak yanıyor.'),
  v('frieren', 'üşümek, donmak', 'to freeze', 'Ich friere ohne Jacke.', 'Ceketsiz üşüyorum.'),
  v('regnen', 'yağmur yağmak', 'to rain', 'Es regnet seit Stunden.', 'Saatlerdir yağmur yağıyor.'),
  v('schneien', 'kar yağmak', 'to snow', 'Im Winter schneit es oft.', 'Kışın sık kar yağar.'),
  v('wecken', 'uyandırmak', 'to wake (someone)', 'Weck mich um sieben.', 'Beni yedide uyandır.'),
  v('klopfen', 'vurmak (kapıya)', 'to knock', 'Jemand klopft an die Tür.', 'Biri kapıyı çalıyor.'),
  v('winken', 'el sallamak', 'to wave', 'Sie winkt zum Abschied.', 'Veda ederken el sallıyor.'),
  v('schütteln', 'sallamak', 'to shake', 'Schüttel die Flasche.', 'Şişeyi salla.'),
  v('küssen', 'öpmek', 'to kiss', 'Sie küsst ihr Kind.', 'Çocuğunu öpüyor.'),
  v('umarmen', 'sarılmak, kucaklamak', 'to hug', 'Er umarmt seine Mutter.', 'Annesine sarılıyor.'),
  v('lügen', 'yalan söylemek', 'to lie', 'Du sollst nicht lügen.', 'Yalan söylememelisin.'),
  v('schweigen', 'susmak', 'to be silent', 'Bitte schweig einen Moment.', 'Lütfen bir an sus.'),
  v('schreien', 'bağırmak', 'to scream', 'Das Baby schreit laut.', 'Bebek yüksek sesle ağlıyor.'),
  v('flüstern', 'fısıldamak', 'to whisper', 'Sie flüstert mir etwas zu.', 'Bana bir şey fısıldıyor.'),
  v('verzeihen', 'affetmek', 'to forgive', 'Verzeih mir bitte.', 'Lütfen beni affet.'),
  v('einsetzen', 'kullanmak, devreye sokmak', 'to use, to deploy', 'Wir setzen neue Methoden ein.', 'Yeni yöntemler kullanıyoruz.'),
  v('beitragen', 'katkıda bulunmak', 'to contribute', 'Jeder kann etwas beitragen.', 'Herkes bir katkı sunabilir.'),
  v('ermöglichen', 'olanak sağlamak', 'to enable', 'Das Stipendium ermöglicht das Studium.', 'Burs, eğitimi mümkün kılıyor.'),

  // ── Movement (more) ─────────────────────────────────────────────────────────
  v('spazieren', 'gezinmek, yürüyüş yapmak', 'to stroll', 'Wir spazieren im Park.', 'Parkta yürüyoruz.'),
  v('wandern', 'doğa yürüyüşü yapmak', 'to hike', 'Im Sommer wandern wir viel.', 'Yazın çok yürüyüş yaparız.'),
  v('joggen', 'koşu yapmak', 'to jog', 'Ich jogge jeden Morgen.', 'Her sabah koşu yaparım.'),
  v('rennen', 'koşmak', 'to run', 'Das Kind rennt zum Bus.', 'Çocuk otobüse koşuyor.'),
  v('kriechen', 'emeklemek, sürünmek', 'to crawl', 'Das Baby kriecht über den Boden.', 'Bebek yerde emekliyor.'),
  v('rutschen', 'kaymak', 'to slide', 'Pass auf, der Boden ist rutschig.', 'Dikkat et, zemin kaygan.'),
  v('stürzen', 'düşmek, devrilmek', 'to fall, to tumble', 'Er ist auf dem Eis gestürzt.', 'Buzda düştü.'),
  v('steigen', 'çıkmak, yükselmek', 'to rise, to climb', 'Die Preise steigen.', 'Fiyatlar yükseliyor.'),
  v('sinken', 'batmak, azalmak', 'to sink, to fall', 'Die Temperatur sinkt.', 'Sıcaklık düşüyor.'),
  v('verschwinden', 'kaybolmak', 'to disappear', 'Die Sonne verschwindet hinter den Wolken.', 'Güneş bulutların arkasında kayboluyor.'),
  v('auftauchen', 'ortaya çıkmak', 'to appear', 'Plötzlich tauchte er auf.', 'Aniden ortaya çıktı.'),
  v('erscheinen', 'görünmek, çıkmak (yayın)', 'to appear', 'Das Buch erscheint im Mai.', 'Kitap mayısta çıkıyor.'),
  v('zittern', 'titremek', 'to tremble', 'Sie zittert vor Kälte.', 'Soğuktan titriyor.'),
  v('hinfallen', 'yere düşmek', 'to fall down', 'Pass auf, du fällst hin!', 'Dikkat et, düşersin!'),
  v('bewegen', 'hareket ettirmek', 'to move', 'Beweg den Stuhl nach links.', 'Sandalyeyi sola çek.'),

  // ── Home & everyday (more) ──────────────────────────────────────────────────
  v('heizen', 'ısıtmak', 'to heat', 'Wir heizen das Haus im Winter.', 'Kışın evi ısıtıyoruz.'),
  v('lüften', 'havalandırmak', 'to air, to ventilate', 'Lüfte das Zimmer am Morgen.', 'Sabah odayı havalandır.'),
  v('fegen', 'süpürmek', 'to sweep', 'Ich fege den Hof.', 'Avluyu süpürüyorum.'),
  v('wischen', 'silmek, paspaslamak', 'to wipe, to mop', 'Sie wischt den Boden.', 'Yeri paspaslıyor.'),
  v('bügeln', 'ütülemek', 'to iron', 'Ich bügle die Hemden.', 'Gömlekleri ütülüyorum.'),
  v('spülen', 'bulaşık yıkamak, durulamak', 'to rinse, to do dishes', 'Wir spülen nach dem Essen.', 'Yemekten sonra bulaşık yıkarız.'),
  v('nähen', 'dikmek', 'to sew', 'Meine Oma näht Kleider.', 'Büyükannem elbise diker.'),
  v('stricken', 'örmek', 'to knit', 'Sie strickt einen Schal.', 'Bir atkı örüyor.'),
  v('basteln', 'el işi yapmak', 'to craft', 'Die Kinder basteln gern.', 'Çocuklar el işi yapmayı sever.'),
  v('kleben', 'yapıştırmak', 'to glue, to stick', 'Kleb das Foto ins Album.', 'Fotoğrafı albüme yapıştır.'),
  v('binden', 'bağlamak', 'to tie', 'Bind deine Schuhe.', 'Ayakkabılarını bağla.'),
  v('graben', 'kazmak', 'to dig', 'Der Hund gräbt ein Loch.', 'Köpek bir çukur kazıyor.'),
  v('pflanzen', 'dikmek (bitki)', 'to plant', 'Wir pflanzen einen Baum.', 'Bir ağaç dikiyoruz.'),
  v('gießen', 'sulamak; dökmek', 'to water; to pour', 'Ich gieße die Blumen.', 'Çiçekleri suluyorum.'),
  v('füttern', 'beslemek (hayvan)', 'to feed', 'Sie füttert die Katze.', 'Kediyi besliyor.'),

  // ── Cooking (more) ──────────────────────────────────────────────────────────
  v('braten', 'kızartmak', 'to fry', 'Ich brate ein Ei.', 'Bir yumurta kızartıyorum.'),
  v('grillen', 'ızgara yapmak', 'to grill', 'Im Sommer grillen wir oft.', 'Yazın sık mangal yaparız.'),
  v('rühren', 'karıştırmak', 'to stir', 'Rühr die Suppe um.', 'Çorbayı karıştır.'),
  v('mischen', 'karıştırmak', 'to mix', 'Misch die Zutaten gut.', 'Malzemeleri iyice karıştır.'),
  v('schälen', 'soymak (kabuk)', 'to peel', 'Ich schäle die Kartoffeln.', 'Patatesleri soyuyorum.'),
  v('aufwärmen', 'ısıtmak (yemek)', 'to warm up', 'Ich wärme die Suppe auf.', 'Çorbayı ısıtıyorum.'),
  v('schmelzen', 'erimek, eritmek', 'to melt', 'Der Schnee schmilzt in der Sonne.', 'Kar güneşte eriyor.'),
  v('tropfen', 'damlamak', 'to drip', 'Der Wasserhahn tropft.', 'Musluk damlıyor.'),

  // ── Technology & office ─────────────────────────────────────────────────────
  v('drucken', 'yazdırmak', 'to print', 'Ich drucke das Dokument.', 'Belgeyi yazdırıyorum.'),
  v('kopieren', 'kopyalamak', 'to copy', 'Kopier bitte diese Seite.', 'Lütfen bu sayfayı kopyala.'),
  v('speichern', 'kaydetmek', 'to save', 'Speichere die Datei.', 'Dosyayı kaydet.'),
  v('löschen', 'silmek', 'to delete', 'Ich lösche die alten Fotos.', 'Eski fotoğrafları siliyorum.'),
  v('herunterladen', 'indirmek', 'to download', 'Lad die App herunter.', 'Uygulamayı indir.'),
  v('hochladen', 'yüklemek', 'to upload', 'Ich lade das Video hoch.', 'Videoyu yüklüyorum.'),
  v('installieren', 'kurmak (yazılım)', 'to install', 'Installiere das Programm.', 'Programı kur.'),
  v('klicken', 'tıklamak', 'to click', 'Klick auf den Knopf.', 'Düğmeye tıkla.'),
  v('tippen', 'yazmak (klavye)', 'to type', 'Sie tippt sehr schnell.', 'Çok hızlı yazıyor.'),
  v('buchen', 'rezervasyon yapmak', 'to book', 'Wir buchen ein Hotel.', 'Bir otel rezervasyonu yapıyoruz.'),
  v('anmelden', 'kaydetmek, kayıt yaptırmak', 'to register', 'Ich melde mich für den Kurs an.', 'Kursa kayıt oluyorum.'),
  v('abmelden', 'kaydı silmek, çıkış yapmak', 'to deregister, to log out', 'Vergiss nicht, dich abzumelden.', 'Çıkış yapmayı unutma.'),
  v('messen', 'ölçmek', 'to measure', 'Der Arzt misst den Blutdruck.', 'Doktor tansiyonu ölçüyor.'),
  v('wiegen', 'tartmak; ağırlığında olmak', 'to weigh', 'Ich wiege das Gepäck.', 'Bagajı tartıyorum.'),

  // ── Social & communication (more) ───────────────────────────────────────────
  v('begrüßen', 'karşılamak, selamlamak', 'to welcome', 'Der Gastgeber begrüßt die Gäste.', 'Ev sahibi misafirleri karşılıyor.'),
  v('zustimmen', 'onaylamak, katılmak', 'to agree', 'Ich stimme dir zu.', 'Sana katılıyorum.'),
  v('ablehnen', 'reddetmek', 'to reject', 'Sie lehnt das Angebot ab.', 'Teklifi reddediyor.'),
  v('akzeptieren', 'kabul etmek', 'to accept', 'Wir akzeptieren die Regeln.', 'Kuralları kabul ediyoruz.'),
  v('widersprechen', 'karşı çıkmak, itiraz etmek', 'to contradict', 'Er widerspricht dem Lehrer.', 'Öğretmene itiraz ediyor.'),
  v('kritisieren', 'eleştirmek', 'to criticise', 'Sie kritisiert den Plan.', 'Planı eleştiriyor.'),
  v('loben', 'övmek', 'to praise', 'Der Chef lobt die Mitarbeiter.', 'Patron çalışanları övüyor.'),
  v('gestehen', 'itiraf etmek', 'to confess', 'Er gesteht seinen Fehler.', 'Hatasını itiraf ediyor.'),
  v('betonen', 'vurgulamak', 'to emphasise', 'Sie betont das wichtige Wort.', 'Önemli kelimeyi vurguluyor.'),
  v('hinweisen', 'işaret etmek, dikkat çekmek', 'to point out', 'Ich weise auf das Problem hin.', 'Soruna dikkat çekiyorum.'),
  v('verraten', 'ele vermek, ifşa etmek', 'to betray, to reveal', 'Verrate mir das Geheimnis.', 'Bana sırrı söyle.'),
  v('begründen', 'gerekçelendirmek', 'to justify', 'Begründe deine Meinung.', 'Görüşünü gerekçelendir.'),
  v('melden', 'bildirmek, haber vermek', 'to report', 'Melde den Schaden der Versicherung.', 'Hasarı sigortaya bildir.'),
  v('nicken', 'baş sallamak (onay)', 'to nod', 'Sie nickt zustimmend.', 'Onaylayarak baş sallıyor.'),
  v('gratulieren', 'tebrik etmek', 'to congratulate', 'Ich gratuliere dir zum Geburtstag.', 'Doğum gününü kutlarım.'),

  // ── Mind & emotion (more) ───────────────────────────────────────────────────
  v('erwarten', 'beklemek (ummak)', 'to expect', 'Ich erwarte einen Anruf.', 'Bir telefon bekliyorum.'),
  v('befürchten', 'endişe etmek, korkmak', 'to fear', 'Ich befürchte das Schlimmste.', 'En kötüsünden korkuyorum.'),
  v('vermuten', 'tahmin etmek, sanmak', 'to suppose', 'Ich vermute, er kommt nicht.', 'Sanırım gelmeyecek.'),
  v('ahnen', 'sezmek', 'to have a feeling', 'Ich habe nichts geahnt.', 'Hiçbir şey sezmedim.'),
  v('spüren', 'hissetmek (fiziksel)', 'to sense', 'Ich spüre den Wind.', 'Rüzgârı hissediyorum.'),
  v('beruhigen', 'sakinleştirmek', 'to calm', 'Die Musik beruhigt mich.', 'Müzik beni sakinleştiriyor.'),
  v('trösten', 'teselli etmek', 'to comfort', 'Sie tröstet das weinende Kind.', 'Ağlayan çocuğu teselli ediyor.'),
  v('ermutigen', 'cesaretlendirmek', 'to encourage', 'Der Lehrer ermutigt die Schüler.', 'Öğretmen öğrencileri cesaretlendiriyor.'),
  v('erschrecken', 'korkutmak, ürkmek', 'to frighten', 'Du hast mich erschreckt!', 'Beni korkuttun!'),
  v('langweilen', 'sıkmak, canını sıkmak', 'to bore', 'Der Film langweilt mich.', 'Film beni sıkıyor.'),
  v('genügen', 'yeterli olmak', 'to be enough', 'Das Geld genügt nicht.', 'Para yeterli değil.'),
  v('bezweifeln', 'kuşku duymak', 'to doubt', 'Ich bezweifle seine Worte.', 'Sözlerinden kuşku duyuyorum.'),
  v('beneiden', 'kıskanmak, gıpta etmek', 'to envy', 'Ich beneide dich um deine Reise.', 'Yolculuğun için seni kıskanıyorum.'),
  v('aushalten', 'dayanmak, katlanmak', 'to endure', 'Ich halte die Hitze nicht aus.', 'Sıcağa dayanamıyorum.'),
  v('ertragen', 'tahammül etmek', 'to bear', 'Sie erträgt den Lärm nicht.', 'Gürültüye tahammül edemiyor.'),

  // ── Work & action (more) ────────────────────────────────────────────────────
  v('einstellen', 'işe almak; ayarlamak', 'to hire; to set', 'Die Firma stellt neue Leute ein.', 'Şirket yeni kişiler işe alıyor.'),
  v('entlassen', 'işten çıkarmak', 'to dismiss', 'Er wurde letzte Woche entlassen.', 'Geçen hafta işten çıkarıldı.'),
  v('befördern', 'terfi ettirmek; taşımak', 'to promote', 'Sie wurde zur Chefin befördert.', 'Müdürlüğe terfi ettirildi.'),
  v('bestimmen', 'belirlemek', 'to determine', 'Der Chef bestimmt die Regeln.', 'Kuralları patron belirler.'),
  v('festlegen', 'saptamak, kararlaştırmak', 'to fix, to set', 'Wir legen das Datum fest.', 'Tarihi saptıyoruz.'),
  v('regeln', 'düzenlemek, halletmek', 'to regulate', 'Die Polizei regelt den Verkehr.', 'Polis trafiği düzenliyor.'),
  v('ordnen', 'düzenlemek, sıralamak', 'to arrange, to order', 'Ordne die Wörter alphabetisch.', 'Kelimeleri alfabetik sırala.'),
  v('sortieren', 'ayıklamak, tasnif etmek', 'to sort', 'Ich sortiere die Dokumente.', 'Belgeleri tasnif ediyorum.'),
  v('erledigen', 'halletmek, bitirmek', 'to deal with, to complete', 'Ich erledige die Arbeit heute.', 'İşi bugün hallediyorum.'),
  v('beschäftigen', 'meşgul etmek; istihdam etmek', 'to occupy, to employ', 'Die Firma beschäftigt 100 Leute.', 'Şirket 100 kişi istihdam ediyor.'),
  v('unterbrechen', 'sözünü kesmek, kesmek', 'to interrupt', 'Unterbrich mich bitte nicht.', 'Lütfen sözümü kesme.'),
  v('fortsetzen', 'sürdürmek', 'to continue', 'Wir setzen die Arbeit morgen fort.', 'İşe yarın devam ediyoruz.'),
  v('abschließen', 'tamamlamak; kilitlemek', 'to complete; to lock', 'Ich schließe das Studium ab.', 'Eğitimi tamamlıyorum.'),
  v('verzögern', 'geciktirmek', 'to delay', 'Der Schnee verzögert den Flug.', 'Kar uçuşu geciktiriyor.'),
  v('beschleunigen', 'hızlandırmak', 'to accelerate', 'Das Auto beschleunigt schnell.', 'Araba hızlı hızlanıyor.'),
  v('bremsen', 'fren yapmak', 'to brake', 'Der Fahrer bremst plötzlich.', 'Sürücü aniden fren yapıyor.'),
  v('parken', 'park etmek', 'to park', 'Ich parke vor dem Haus.', 'Evin önüne park ediyorum.'),
  v('starten', 'başlatmak, kalkış yapmak', 'to start', 'Das Flugzeug startet um zehn.', 'Uçak onda kalkıyor.'),
  v('liefern', 'teslim etmek, getirmek', 'to deliver', 'Sie liefern die Pizza nach Hause.', 'Pizzayı eve teslim ediyorlar.'),
  v('verteilen', 'dağıtmak', 'to distribute', 'Der Lehrer verteilt die Blätter.', 'Öğretmen kâğıtları dağıtıyor.'),

  // ── Change & creation (more) ────────────────────────────────────────────────
  v('zerstören', 'yıkmak, yok etmek', 'to destroy', 'Der Sturm zerstört die Häuser.', 'Fırtına evleri yıkıyor.'),
  v('zerbrechen', 'kırmak, kırılmak', 'to shatter', 'Das Glas ist zerbrochen.', 'Bardak kırıldı.'),
  v('renovieren', 'yenilemek, tadilat yapmak', 'to renovate', 'Wir renovieren die Küche.', 'Mutfağı yeniliyoruz.'),
  v('streichen', 'boyamak; silmek (üstünü çizmek)', 'to paint; to cross out', 'Wir streichen die Wand weiß.', 'Duvarı beyaza boyuyoruz.'),
  v('erfinden', 'icat etmek', 'to invent', 'Wer hat das Telefon erfunden?', 'Telefonu kim icat etti?'),
  v('entdecken', 'keşfetmek', 'to discover', 'Sie entdeckt einen Fehler.', 'Bir hata keşfediyor.'),
  v('untersuchen', 'incelemek, muayene etmek', 'to examine', 'Der Arzt untersucht den Patienten.', 'Doktor hastayı muayene ediyor.'),
  v('verbreiten', 'yaymak', 'to spread', 'Das Internet verbreitet Nachrichten schnell.', 'İnternet haberleri hızlı yayar.'),
  v('blühen', 'çiçek açmak', 'to bloom', 'Im Frühling blühen die Blumen.', 'İlkbaharda çiçekler açar.'),
  v('abnehmen', 'kilo vermek; almak (telefon)', 'to lose weight', 'Ich möchte abnehmen.', 'Kilo vermek istiyorum.'),
  v('zunehmen', 'kilo almak; artmak', 'to gain weight, to increase', 'Die Zahl der Studenten nimmt zu.', 'Öğrenci sayısı artıyor.'),
  v('verschwenden', 'israf etmek', 'to waste', 'Verschwende kein Wasser.', 'Su israf etme.'),
  v('verpassen', 'kaçırmak', 'to miss', 'Ich habe den Bus verpasst.', 'Otobüsü kaçırdım.'),
  v('erwischen', 'yakalamak', 'to catch', 'Die Polizei erwischt den Dieb.', 'Polis hırsızı yakalıyor.'),
  v('schaden', 'zarar vermek', 'to harm', 'Rauchen schadet der Gesundheit.', 'Sigara sağlığa zarar verir.'),
  v('dienen', 'hizmet etmek; yaramak', 'to serve', 'Das dient als Beispiel.', 'Bu örnek olarak yarar.'),
  v('verteidigen', 'savunmak', 'to defend', 'Er verteidigt seine Meinung.', 'Görüşünü savunuyor.'),
  v('angreifen', 'saldırmak', 'to attack', 'Der Hund greift den Fremden an.', 'Köpek yabancıya saldırıyor.'),
  v('kämpfen', 'savaşmak, mücadele etmek', 'to fight', 'Sie kämpfen für ihre Rechte.', 'Hakları için mücadele ediyorlar.'),
  v('fliehen', 'kaçmak', 'to flee', 'Die Menschen fliehen vor dem Krieg.', 'İnsanlar savaştan kaçıyor.'),
];
