// Extended German vocabulary — adjectives, adverbs and everyday phrases.
// Hand-checked Turkish meanings; no article (only nouns carry one).
import type { CuratedWord } from '@/lib/mock-data';

const w = (
  word: string,
  type: 'adjective' | 'adverb' | 'phrase',
  tr: string,
  en: string,
): CuratedWord => ({ id: word, word, language: 'de', type, shortDef: { tr, en } });

const adj = (word: string, tr: string, en: string) => w(word, 'adjective', tr, en);
const adv = (word: string, tr: string, en: string) => w(word, 'adverb', tr, en);
const phr = (word: string, tr: string, en: string) => w(word, 'phrase', tr, en);

// ─── Adjectives ───────────────────────────────────────────────────────────────
export const GERMAN_ADJECTIVES: CuratedWord[] = [
  adj('groß', 'büyük', 'big, large'),
  adj('klein', 'küçük', 'small'),
  adj('schlecht', 'kötü', 'bad'),
  adj('neu', 'yeni', 'new'),
  adj('alt', 'eski, yaşlı', 'old'),
  adj('jung', 'genç', 'young'),
  adj('lang', 'uzun', 'long'),
  adj('kurz', 'kısa', 'short'),
  adj('hoch', 'yüksek', 'high'),
  adj('breit', 'geniş', 'wide'),
  adj('dick', 'kalın, şişman', 'thick, fat'),
  adj('dünn', 'ince', 'thin'),
  adj('schwer', 'ağır, zor', 'heavy, hard'),
  adj('leicht', 'hafif, kolay', 'light, easy'),
  adj('stark', 'güçlü, kuvvetli', 'strong'),
  adj('schwach', 'zayıf', 'weak'),
  adj('langsam', 'yavaş', 'slow'),
  adj('warm', 'sıcak, ılık', 'warm'),
  adj('kalt', 'soğuk', 'cold'),
  adj('heiß', 'çok sıcak', 'hot'),
  adj('kühl', 'serin', 'cool'),
  adj('hell', 'aydınlık, açık (renk)', 'bright, light'),
  adj('dunkel', 'karanlık, koyu', 'dark'),
  adj('laut', 'gürültülü, sesli', 'loud'),
  adj('leise', 'sessiz, alçak sesli', 'quiet'),
  adj('sauber', 'temiz', 'clean'),
  adj('schmutzig', 'kirli', 'dirty'),
  adj('hässlich', 'çirkin', 'ugly'),
  adj('reich', 'zengin', 'rich'),
  adj('arm', 'fakir, yoksul', 'poor'),
  adj('teuer', 'pahalı', 'expensive'),
  adj('billig', 'ucuz', 'cheap'),
  adj('günstig', 'uygun fiyatlı', 'affordable'),
  adj('voll', 'dolu', 'full'),
  adj('leer', 'boş', 'empty'),
  adj('offen', 'açık', 'open'),
  adj('früh', 'erken', 'early'),
  adj('spät', 'geç', 'late'),
  adj('richtig', 'doğru', 'correct'),
  adj('falsch', 'yanlış', 'wrong'),
  adj('wichtig', 'önemli', 'important'),
  adj('möglich', 'mümkün', 'possible'),
  adj('nötig', 'gerekli', 'necessary'),
  adj('fertig', 'hazır, bitmiş', 'ready, finished'),
  adj('müde', 'yorgun', 'tired'),
  adj('krank', 'hasta', 'sick'),
  adj('gesund', 'sağlıklı', 'healthy'),
  adj('glücklich', 'mutlu', 'happy'),
  adj('traurig', 'üzgün', 'sad'),
  adj('wütend', 'öfkeli, kızgın', 'angry'),
  adj('ruhig', 'sakin', 'calm'),
  adj('nervös', 'gergin, sinirli', 'nervous'),
  adj('freundlich', 'arkadaş canlısı, dostça', 'friendly'),
  adj('nett', 'hoş, kibar', 'nice'),
  adj('höflich', 'kibar, nazik', 'polite'),
  adj('klug', 'zeki, akıllı', 'clever'),
  adj('dumm', 'aptal, ahmak', 'stupid'),
  adj('fleißig', 'çalışkan', 'diligent'),
  adj('faul', 'tembel', 'lazy'),
  adj('lustig', 'komik, eğlenceli', 'funny'),
  adj('ernst', 'ciddi', 'serious'),
  adj('interessant', 'ilginç', 'interesting'),
  adj('langweilig', 'sıkıcı', 'boring'),
  adj('einfach', 'basit, kolay; (partikül) sadece, basitçe', 'simple, easy; (particle) simply, just'),
  adj('schwierig', 'zor', 'difficult'),
  adj('bekannt', 'tanınmış, bilinen', 'known'),
  adj('berühmt', 'ünlü', 'famous'),
  adj('modern', 'modern', 'modern'),
  adj('frei', 'özgür, boş', 'free'),
  adj('beschäftigt', 'meşgul', 'busy'),
  adj('wahr', 'doğru, gerçek', 'true'),
  adj('echt', 'gerçek, hakiki', 'real, genuine'),
  adj('tief', 'derin', 'deep'),
  adj('nah', 'yakın', 'near'),
  adj('weit', 'uzak, geniş', 'far, wide'),
  adj('bunt', 'rengârenk', 'colourful'),
  adj('hungrig', 'aç', 'hungry'),
  adj('durstig', 'susamış', 'thirsty'),
  adj('satt', 'tok', 'full, sated'),
  adj('lecker', 'lezzetli', 'delicious'),
  adj('süß', 'tatlı', 'sweet'),
  adj('sauer', 'ekşi', 'sour'),
  adj('bitter', 'acı', 'bitter'),
  adj('weich', 'yumuşak', 'soft'),
  adj('hart', 'sert', 'hard'),
  adj('nass', 'ıslak', 'wet'),
  adj('trocken', 'kuru', 'dry'),
];

// ─── Adverbs & common particles ──────────────────────────────────────────────
export const GERMAN_ADVERBS: CuratedWord[] = [
  adv('heute', 'bugün', 'today'),
  adv('morgen', 'yarın', 'tomorrow'),
  adv('gestern', 'dün', 'yesterday'),
  adv('jetzt', 'şimdi', 'now'),
  adv('bald', 'yakında', 'soon'),
  adv('nie', 'asla, hiç', 'never'),
  adv('oft', 'sık sık', 'often'),
  adv('manchmal', 'bazen', 'sometimes'),
  adv('selten', 'nadiren', 'rarely'),
  adv('hier', 'burada', 'here'),
  adv('dort', 'orada', 'there'),
  adv('überall', 'her yerde', 'everywhere'),
  adv('ganz', 'tamamen', 'completely'),
  adv('ziemlich', 'oldukça', 'quite'),
  adv('fast', 'neredeyse', 'almost'),
  adv('genug', 'yeterince', 'enough'),
  adv('wieder', 'tekrar, yine', 'again'),
  adv('natürlich', 'tabii ki, elbette', 'of course'),
  adv('leider', 'maalesef, ne yazık ki', 'unfortunately'),
  adv('hoffentlich', 'umarım', 'hopefully'),
  adv('sofort', 'hemen, derhal', 'immediately'),
  adv('endlich', 'sonunda', 'finally'),
  adv('zusammen', 'birlikte', 'together'),
  adv('allein', 'yalnız, tek başına', 'alone'),
  adv('draußen', 'dışarıda', 'outside'),
  adv('drinnen', 'içeride', 'inside'),
  adv('links', 'solda, sola', 'left'),
  adv('rechts', 'sağda, sağa', 'right'),
  adv('geradeaus', 'düz, dosdoğru', 'straight ahead'),
];

// ─── Everyday phrases ────────────────────────────────────────────────────────
export const GERMAN_PHRASES: CuratedWord[] = [
  phr('guten Morgen', 'günaydın', 'good morning'),
  phr('guten Abend', 'iyi akşamlar', 'good evening'),
  phr('gute Nacht', 'iyi geceler', 'good night'),
  phr('wie geht es dir', 'nasılsın', 'how are you (informal)'),
  phr('wie geht es Ihnen', 'nasılsınız', 'how are you (formal)'),
  phr('danke', 'teşekkürler', 'thank you'),
  phr('bitte', 'rica ederim; lütfen', 'please; you are welcome'),
  phr('entschuldigung', 'özür dilerim, affedersiniz', 'excuse me, sorry'),
  phr('es tut mir leid', 'üzgünüm', 'I am sorry'),
  phr('kein Problem', 'sorun değil', 'no problem'),
  phr('alles klar', 'her şey yolunda, tamam', 'all good, okay'),
  phr('viel Glück', 'bol şans', 'good luck'),
  phr('herzlichen Glückwunsch', 'tebrikler', 'congratulations'),
  phr('bis bald', 'yakında görüşürüz', 'see you soon'),
  phr('bis später', 'sonra görüşürüz', 'see you later'),
  phr('willkommen', 'hoş geldin', 'welcome'),
  phr('ich liebe dich', 'seni seviyorum', 'I love you'),
  phr('wie heißt du', 'adın ne', 'what is your name (informal)'),
  phr('wie heißen Sie', 'adınız ne', 'what is your name (formal)'),
  phr('woher kommst du', 'nerelisin', 'where are you from (informal)'),
  phr('woher kommen Sie', 'nerelisiniz', 'where are you from (formal)'),
  phr('kannst du mir helfen', 'bana yardım edebilir misin', 'can you help me (informal)'),
  phr('können Sie mir helfen', 'bana yardım edebilir misiniz', 'can you help me (formal)'),
  phr('sprichst du Englisch', 'İngilizce konuşur musun', 'do you speak English (informal)'),
  phr('sprechen Sie Englisch', 'İngilizce konuşur musunuz', 'do you speak English (formal)'),
  phr('darf ich dich etwas fragen', 'sana bir şey sorabilir miyim', 'may I ask you (informal)'),
  phr('darf ich Sie etwas fragen', 'size bir şey sorabilir miyim', 'may I ask you (formal)'),
  phr('hast du Zeit', 'vaktin var mı', 'do you have time (informal)'),
  phr('haben Sie Zeit', 'vaktiniz var mı', 'do you have time (formal)'),
  phr('was machst du', 'ne yapıyorsun', 'what are you doing (informal)'),
  phr('was machen Sie', 'ne yapıyorsunuz', 'what are you doing (formal)'),
  phr('wo wohnen Sie', 'nerede oturuyorsunuz', 'where do you live (formal)'),
  phr('wie alt bist du', 'kaç yaşındasın', 'how old are you (informal)'),
  phr('wie alt sind Sie', 'kaç yaşındasınız', 'how old are you (formal)'),
  phr('warte mal', 'bir saniye, dur', 'wait a moment (informal)'),
  phr('warten Sie bitte', 'lütfen bekleyin', 'please wait (formal)'),
  phr('komm her', 'buraya gel', 'come here (informal)'),
  phr('kommen Sie bitte', 'lütfen gelin', 'please come (formal)'),
  phr('schau mal', 'bir bak', 'have a look (informal)'),
  phr('schauen Sie bitte', 'lütfen bakın', 'please look (formal)'),
  phr('ich verstehe nicht', 'anlamıyorum', 'I do not understand'),
  phr('wie viel kostet das', 'bunun fiyatı ne kadar', 'how much does this cost'),
  phr('wo ist die Toilette', 'tuvalet nerede', 'where is the toilet'),
  phr('ich hätte gern', 'şunu istiyorum (rica)', 'I would like'),
  phr('keine Ahnung', 'hiçbir fikrim yok', 'no idea'),
  phr('mach’s gut', 'kendine iyi bak', 'take care'),
];
