// German noun bank for the "Artikeller" category — 200+ common nouns with
// their article (der/die/das) and Turkish meaning. The whole point of this
// list is teaching genders, so each entry leads with its article.
import type { CuratedWord } from '@/lib/mock-data';

const n = (word: string, article: string, tr: string, en: string): CuratedWord => ({
  id: word,
  word,
  language: 'de',
  type: 'noun',
  article,
  shortDef: { tr, en },
});

export const GERMAN_NOUNS: CuratedWord[] = [
  // People & family
  n('Mann', 'der', 'adam, erkek', 'man'),
  n('Frau', 'die', 'kadın', 'woman'),
  n('Kind', 'das', 'çocuk', 'child'),
  n('Junge', 'der', 'oğlan', 'boy'),
  n('Mädchen', 'das', 'kız çocuğu', 'girl'),
  n('Sohn', 'der', 'oğul', 'son'),
  n('Tochter', 'die', 'kız evlat', 'daughter'),
  n('Opa', 'der', 'dede', 'grandpa'),
  n('Oma', 'die', 'babaanne, anneanne', 'grandma'),
  n('Onkel', 'der', 'amca, dayı', 'uncle'),
  n('Tante', 'die', 'teyze, hala', 'aunt'),
  n('Mensch', 'der', 'insan', 'human, person'),
  n('Lehrer', 'der', 'öğretmen', 'teacher'),
  n('Schüler', 'der', 'öğrenci', 'pupil'),
  n('Student', 'der', 'üniversite öğrencisi', 'student'),
  n('Arzt', 'der', 'doktor', 'doctor'),
  n('Nachbar', 'der', 'komşu', 'neighbour'),
  n('Chef', 'der', 'patron, şef', 'boss'),
  n('Kollege', 'der', 'iş arkadaşı', 'colleague'),
  n('Baby', 'das', 'bebek', 'baby'),
  n('Gast', 'der', 'misafir', 'guest'),
  n('Familie', 'die', 'aile', 'family'),
  n('Leute', 'die', 'insanlar, halk', 'people'),
  n('Name', 'der', 'isim, ad', 'name'),
  // Body
  n('Kopf', 'der', 'baş, kafa', 'head'),
  n('Gesicht', 'das', 'yüz', 'face'),
  n('Auge', 'das', 'göz', 'eye'),
  n('Ohr', 'das', 'kulak', 'ear'),
  n('Nase', 'die', 'burun', 'nose'),
  n('Mund', 'der', 'ağız', 'mouth'),
  n('Zahn', 'der', 'diş', 'tooth'),
  n('Zunge', 'die', 'dil (organ)', 'tongue'),
  n('Hals', 'der', 'boyun, boğaz', 'neck, throat'),
  n('Schulter', 'die', 'omuz', 'shoulder'),
  n('Arm', 'der', 'kol', 'arm'),
  n('Hand', 'die', 'el', 'hand'),
  n('Finger', 'der', 'parmak', 'finger'),
  n('Bauch', 'der', 'karın', 'belly'),
  n('Rücken', 'der', 'sırt', 'back'),
  n('Bein', 'das', 'bacak', 'leg'),
  n('Knie', 'das', 'diz', 'knee'),
  n('Herz', 'das', 'kalp', 'heart'),
  n('Haar', 'das', 'saç', 'hair'),
  n('Blut', 'das', 'kan', 'blood'),
  // House & furniture
  n('Zimmer', 'das', 'oda', 'room'),
  n('Küche', 'die', 'mutfak', 'kitchen'),
  n('Schlafzimmer', 'das', 'yatak odası', 'bedroom'),
  n('Wohnzimmer', 'das', 'oturma odası', 'living room'),
  n('Tür', 'die', 'kapı', 'door'),
  n('Fenster', 'das', 'pencere', 'window'),
  n('Wand', 'die', 'duvar', 'wall'),
  n('Boden', 'der', 'zemin', 'floor'),
  n('Dach', 'das', 'çatı', 'roof'),
  n('Treppe', 'die', 'merdiven', 'stairs'),
  n('Bett', 'das', 'yatak', 'bed'),
  n('Tisch', 'der', 'masa', 'table'),
  n('Stuhl', 'der', 'sandalye', 'chair'),
  n('Sofa', 'das', 'koltuk, kanepe', 'sofa'),
  n('Schrank', 'der', 'dolap', 'cupboard, wardrobe'),
  n('Regal', 'das', 'raf', 'shelf'),
  n('Lampe', 'die', 'lamba', 'lamp'),
  n('Spiegel', 'der', 'ayna', 'mirror'),
  n('Teppich', 'der', 'halı', 'carpet'),
  n('Garten', 'der', 'bahçe', 'garden'),
  n('Schlüssel', 'der', 'anahtar', 'key'),
  n('Uhr', 'die', 'saat', 'clock, watch'),
  // Food & drink
  n('Brot', 'das', 'ekmek', 'bread'),
  n('Butter', 'die', 'tereyağı', 'butter'),
  n('Käse', 'der', 'peynir', 'cheese'),
  n('Ei', 'das', 'yumurta', 'egg'),
  n('Fleisch', 'das', 'et', 'meat'),
  n('Wurst', 'die', 'sosis, sucuk', 'sausage'),
  n('Fisch', 'der', 'balık', 'fish'),
  n('Apfel', 'der', 'elma', 'apple'),
  n('Banane', 'die', 'muz', 'banana'),
  n('Orange', 'die', 'portakal', 'orange'),
  n('Birne', 'die', 'armut', 'pear'),
  n('Kartoffel', 'die', 'patates', 'potato'),
  n('Tomate', 'die', 'domates', 'tomato'),
  n('Zwiebel', 'die', 'soğan', 'onion'),
  n('Salat', 'der', 'salata', 'salad'),
  n('Reis', 'der', 'pirinç', 'rice'),
  n('Suppe', 'die', 'çorba', 'soup'),
  n('Kuchen', 'der', 'kek, pasta', 'cake'),
  n('Zucker', 'der', 'şeker', 'sugar'),
  n('Salz', 'das', 'tuz', 'salt'),
  n('Honig', 'der', 'bal', 'honey'),
  n('Kaffee', 'der', 'kahve', 'coffee'),
  n('Tee', 'der', 'çay', 'tea'),
  n('Milch', 'die', 'süt', 'milk'),
  n('Saft', 'der', 'meyve suyu', 'juice'),
  n('Bier', 'das', 'bira', 'beer'),
  n('Wein', 'der', 'şarap', 'wine'),
  n('Essen', 'das', 'yemek', 'food, meal'),
  // Nature & animals
  n('Baum', 'der', 'ağaç', 'tree'),
  n('Blume', 'die', 'çiçek', 'flower'),
  n('Gras', 'das', 'çimen, ot', 'grass'),
  n('Blatt', 'das', 'yaprak', 'leaf'),
  n('Wald', 'der', 'orman', 'forest'),
  n('Berg', 'der', 'dağ', 'mountain'),
  n('Tal', 'das', 'vadi', 'valley'),
  n('Fluss', 'der', 'nehir', 'river'),
  n('See', 'der', 'göl', 'lake'),
  n('Meer', 'das', 'deniz', 'sea'),
  n('Strand', 'der', 'plaj, kumsal', 'beach'),
  n('Insel', 'die', 'ada', 'island'),
  n('Himmel', 'der', 'gökyüzü', 'sky'),
  n('Sonne', 'die', 'güneş', 'sun'),
  n('Mond', 'der', 'ay', 'moon'),
  n('Stern', 'der', 'yıldız', 'star'),
  n('Wolke', 'die', 'bulut', 'cloud'),
  n('Regen', 'der', 'yağmur', 'rain'),
  n('Schnee', 'der', 'kar', 'snow'),
  n('Wind', 'der', 'rüzgâr', 'wind'),
  n('Feuer', 'das', 'ateş', 'fire'),
  n('Erde', 'die', 'dünya, toprak', 'earth, soil'),
  n('Hund', 'der', 'köpek', 'dog'),
  n('Katze', 'die', 'kedi', 'cat'),
  n('Vogel', 'der', 'kuş', 'bird'),
  n('Pferd', 'das', 'at', 'horse'),
  n('Kuh', 'die', 'inek', 'cow'),
  n('Schwein', 'das', 'domuz', 'pig'),
  n('Schaf', 'das', 'koyun', 'sheep'),
  n('Maus', 'die', 'fare', 'mouse'),
  n('Bär', 'der', 'ayı', 'bear'),
  n('Löwe', 'der', 'aslan', 'lion'),
  n('Elefant', 'der', 'fil', 'elephant'),
  n('Affe', 'der', 'maymun', 'monkey'),
  // Clothing
  n('Hemd', 'das', 'gömlek', 'shirt'),
  n('Hose', 'die', 'pantolon', 'trousers'),
  n('Rock', 'der', 'etek', 'skirt'),
  n('Kleid', 'das', 'elbise', 'dress'),
  n('Jacke', 'die', 'ceket', 'jacket'),
  n('Mantel', 'der', 'palto', 'coat'),
  n('Pullover', 'der', 'kazak', 'sweater'),
  n('Schuh', 'der', 'ayakkabı', 'shoe'),
  n('Stiefel', 'der', 'bot, çizme', 'boot'),
  n('Socke', 'die', 'çorap', 'sock'),
  n('Hut', 'der', 'şapka', 'hat'),
  n('Mütze', 'die', 'bere', 'cap'),
  n('Schal', 'der', 'atkı', 'scarf'),
  n('Handschuh', 'der', 'eldiven', 'glove'),
  n('Brille', 'die', 'gözlük', 'glasses'),
  n('Tasche', 'die', 'çanta', 'bag'),
  // Time & seasons
  n('Tag', 'der', 'gün', 'day'),
  n('Nacht', 'die', 'gece', 'night'),
  n('Morgen', 'der', 'sabah', 'morning'),
  n('Mittag', 'der', 'öğle', 'noon'),
  n('Abend', 'der', 'akşam', 'evening'),
  n('Woche', 'die', 'hafta', 'week'),
  n('Monat', 'der', 'ay (takvim)', 'month'),
  n('Jahr', 'das', 'yıl', 'year'),
  n('Stunde', 'die', 'saat (süre)', 'hour'),
  n('Minute', 'die', 'dakika', 'minute'),
  n('Sekunde', 'die', 'saniye', 'second'),
  n('Frühling', 'der', 'ilkbahar', 'spring'),
  n('Sommer', 'der', 'yaz', 'summer'),
  n('Herbst', 'der', 'sonbahar', 'autumn'),
  n('Winter', 'der', 'kış', 'winter'),
  // City & places
  n('Stadt', 'die', 'şehir', 'city'),
  n('Dorf', 'das', 'köy', 'village'),
  n('Land', 'das', 'ülke', 'country'),
  n('Straße', 'die', 'cadde, sokak', 'street'),
  n('Weg', 'der', 'yol', 'way, path'),
  n('Platz', 'der', 'meydan, yer', 'square, place'),
  n('Brücke', 'die', 'köprü', 'bridge'),
  n('Schule', 'die', 'okul', 'school'),
  n('Universität', 'die', 'üniversite', 'university'),
  n('Krankenhaus', 'das', 'hastane', 'hospital'),
  n('Apotheke', 'die', 'eczane', 'pharmacy'),
  n('Bahnhof', 'der', 'tren istasyonu', 'train station'),
  n('Flughafen', 'der', 'havalimanı', 'airport'),
  n('Kirche', 'die', 'kilise', 'church'),
  n('Museum', 'das', 'müze', 'museum'),
  n('Park', 'der', 'park', 'park'),
  n('Markt', 'der', 'pazar, market', 'market'),
  n('Geschäft', 'das', 'dükkân, mağaza', 'shop'),
  n('Restaurant', 'das', 'restoran', 'restaurant'),
  n('Hotel', 'das', 'otel', 'hotel'),
  n('Bank', 'die', 'banka; bank, sıra', 'bank; bench'),
  n('Post', 'die', 'postane', 'post office'),
  n('Bibliothek', 'die', 'kütüphane', 'library'),
  n('Büro', 'das', 'ofis, büro', 'office'),
  n('Kino', 'das', 'sinema', 'cinema'),
  n('Theater', 'das', 'tiyatro', 'theatre'),
  // Transport
  n('Auto', 'das', 'araba', 'car'),
  n('Bus', 'der', 'otobüs', 'bus'),
  n('Zug', 'der', 'tren', 'train'),
  n('Fahrrad', 'das', 'bisiklet', 'bicycle'),
  n('Flugzeug', 'das', 'uçak', 'aeroplane'),
  n('Schiff', 'das', 'gemi', 'ship'),
  n('Boot', 'das', 'tekne, sandal', 'boat'),
  n('Motorrad', 'das', 'motosiklet', 'motorcycle'),
  // School & work
  n('Stift', 'der', 'kalem', 'pen'),
  n('Bleistift', 'der', 'kurşun kalem', 'pencil'),
  n('Heft', 'das', 'defter', 'notebook'),
  n('Papier', 'das', 'kâğıt', 'paper'),
  n('Tafel', 'die', 'tahta', 'board'),
  n('Schere', 'die', 'makas', 'scissors'),
  n('Computer', 'der', 'bilgisayar', 'computer'),
  n('Handy', 'das', 'cep telefonu', 'mobile phone'),
  n('Telefon', 'das', 'telefon', 'telephone'),
  n('Brief', 'der', 'mektup', 'letter'),
  n('Zeitung', 'die', 'gazete', 'newspaper'),
  n('Wort', 'das', 'kelime', 'word'),
  n('Satz', 'der', 'cümle', 'sentence'),
  n('Frage', 'die', 'soru', 'question'),
  n('Antwort', 'die', 'cevap', 'answer'),
  n('Sprache', 'die', 'dil', 'language'),
  n('Prüfung', 'die', 'sınav', 'exam'),
  n('Aufgabe', 'die', 'görev, ödev', 'task'),
  n('Beruf', 'der', 'meslek', 'profession'),
  n('Arbeit', 'die', 'iş, çalışma', 'work'),
  n('Geld', 'das', 'para', 'money'),
  n('Preis', 'der', 'fiyat, ödül', 'price, prize'),
  n('Plan', 'der', 'plan', 'plan'),
  // Abstract & misc
  n('Leben', 'das', 'hayat', 'life'),
  n('Tod', 'der', 'ölüm', 'death'),
  n('Welt', 'die', 'dünya', 'world'),
  n('Traum', 'der', 'rüya, hayal', 'dream'),
  n('Idee', 'die', 'fikir', 'idea'),
  n('Glück', 'das', 'şans, mutluluk', 'luck, happiness'),
  n('Hoffnung', 'die', 'umut', 'hope'),
  n('Angst', 'die', 'korku', 'fear'),
  n('Freude', 'die', 'sevinç, neşe', 'joy'),
  n('Wahrheit', 'die', 'gerçek, hakikat', 'truth'),
  n('Kraft', 'die', 'güç, kuvvet', 'strength'),
  n('Frieden', 'der', 'barış', 'peace'),
  n('Krieg', 'der', 'savaş', 'war'),
  n('Musik', 'die', 'müzik', 'music'),
  n('Kunst', 'die', 'sanat', 'art'),
  n('Spiel', 'das', 'oyun', 'game'),
  n('Sport', 'der', 'spor', 'sport'),
  n('Wetter', 'das', 'hava durumu', 'weather'),
  n('Farbe', 'die', 'renk', 'colour'),
  n('Zahl', 'die', 'sayı', 'number'),
  n('Problem', 'das', 'sorun', 'problem'),
  n('Geschichte', 'die', 'tarih, hikâye', 'history, story'),
  n('Beispiel', 'das', 'örnek', 'example'),
  n('Grund', 'der', 'sebep, neden', 'reason'),
  n('Sache', 'die', 'şey, konu', 'thing, matter'),
  n('Gefühl', 'das', 'duygu', 'feeling'),
  n('Gedanke', 'der', 'düşünce', 'thought'),
  n('Wille', 'der', 'irade, istek', 'will'),
  // Body & health
  n('Daumen', 'der', 'başparmak', 'thumb'),
  n('Ellbogen', 'der', 'dirsek', 'elbow'),
  n('Magen', 'der', 'mide', 'stomach'),
  n('Lunge', 'die', 'akciğer', 'lung'),
  n('Gehirn', 'das', 'beyin', 'brain'),
  n('Haut', 'die', 'cilt, deri', 'skin'),
  n('Knochen', 'der', 'kemik', 'bone'),
  n('Träne', 'die', 'gözyaşı', 'tear'),
  n('Stimme', 'die', 'ses', 'voice'),
  n('Gesundheit', 'die', 'sağlık', 'health'),
  n('Krankheit', 'die', 'hastalık', 'illness'),
  n('Schmerz', 'der', 'acı, ağrı', 'pain'),
  // Food & drink
  n('Mehl', 'das', 'un', 'flour'),
  n('Öl', 'das', 'yağ', 'oil'),
  n('Joghurt', 'der', 'yoğurt', 'yoghurt'),
  n('Sahne', 'die', 'krema', 'cream'),
  n('Marmelade', 'die', 'reçel', 'jam'),
  n('Schokolade', 'die', 'çikolata', 'chocolate'),
  n('Nuss', 'die', 'fındık, ceviz', 'nut'),
  n('Zitrone', 'die', 'limon', 'lemon'),
  n('Kirsche', 'die', 'kiraz', 'cherry'),
  n('Gurke', 'die', 'salatalık', 'cucumber'),
  n('Karotte', 'die', 'havuç', 'carrot'),
  n('Knoblauch', 'der', 'sarımsak', 'garlic'),
  n('Mahlzeit', 'die', 'öğün', 'meal'),
  // Places
  n('Wohnung', 'die', 'daire', 'flat, apartment'),
  n('Gebäude', 'das', 'bina', 'building'),
  n('Fabrik', 'die', 'fabrika', 'factory'),
  n('Zoo', 'der', 'hayvanat bahçesi', 'zoo'),
  n('Stadion', 'das', 'stadyum', 'stadium'),
  n('Schwimmbad', 'das', 'yüzme havuzu', 'swimming pool'),
  n('Spielplatz', 'der', 'oyun parkı', 'playground'),
  n('Grenze', 'die', 'sınır', 'border'),
  n('Hauptstadt', 'die', 'başkent', 'capital city'),
  n('Zentrum', 'das', 'merkez', 'centre'),
  n('Ecke', 'die', 'köşe', 'corner'),
  n('Eingang', 'der', 'giriş', 'entrance'),
  n('Ausgang', 'der', 'çıkış', 'exit'),
  // Nature & animals
  n('Luft', 'die', 'hava', 'air'),
  n('Eis', 'das', 'buz, dondurma', 'ice, ice cream'),
  n('Sand', 'der', 'kum', 'sand'),
  n('Stein', 'der', 'taş', 'stone'),
  n('Felsen', 'der', 'kaya', 'rock'),
  n('Höhle', 'die', 'mağara', 'cave'),
  n('Wüste', 'die', 'çöl', 'desert'),
  n('Pflanze', 'die', 'bitki', 'plant'),
  n('Wurzel', 'die', 'kök', 'root'),
  n('Ast', 'der', 'dal', 'branch'),
  n('Frucht', 'die', 'meyve', 'fruit'),
  n('Tier', 'das', 'hayvan', 'animal'),
  n('Schmetterling', 'der', 'kelebek', 'butterfly'),
  n('Biene', 'die', 'arı', 'bee'),
  n('Ameise', 'die', 'karınca', 'ant'),
  n('Spinne', 'die', 'örümcek', 'spider'),
  n('Schlange', 'die', 'yılan', 'snake'),
  n('Frosch', 'der', 'kurbağa', 'frog'),
  n('Wolf', 'der', 'kurt', 'wolf'),
  n('Kaninchen', 'das', 'tavşan', 'rabbit'),
  n('Ziege', 'die', 'keçi', 'goat'),
  n('Ente', 'die', 'ördek', 'duck'),
  n('Huhn', 'das', 'tavuk', 'chicken'),
  // Household objects
  n('Löffel', 'der', 'kaşık', 'spoon'),
  n('Gabel', 'die', 'çatal', 'fork'),
  n('Messer', 'das', 'bıçak', 'knife'),
  n('Teller', 'der', 'tabak', 'plate'),
  n('Tasse', 'die', 'fincan', 'cup'),
  n('Glas', 'das', 'bardak, cam', 'glass'),
  n('Flasche', 'die', 'şişe', 'bottle'),
  n('Topf', 'der', 'tencere', 'pot'),
  n('Pfanne', 'die', 'tava', 'pan'),
  n('Seife', 'die', 'sabun', 'soap'),
  n('Handtuch', 'das', 'havlu', 'towel'),
  n('Kissen', 'das', 'yastık', 'pillow'),
  n('Vorhang', 'der', 'perde', 'curtain'),
  n('Kerze', 'die', 'mum', 'candle'),
  n('Bild', 'das', 'resim', 'picture'),
  n('Foto', 'das', 'fotoğraf', 'photo'),
  // Abstract & society
  n('Meinung', 'die', 'görüş, fikir', 'opinion'),
  n('Entscheidung', 'die', 'karar', 'decision'),
  n('Erfahrung', 'die', 'deneyim', 'experience'),
  n('Ziel', 'das', 'hedef, amaç', 'goal'),
  n('Erfolg', 'der', 'başarı', 'success'),
  n('Fehler', 'der', 'hata', 'mistake'),
  n('Lösung', 'die', 'çözüm', 'solution'),
  n('Gefahr', 'die', 'tehlike', 'danger'),
  n('Freiheit', 'die', 'özgürlük', 'freedom'),
  n('Nachricht', 'die', 'haber, mesaj', 'news, message'),
  n('Gesetz', 'das', 'yasa, kanun', 'law'),
  n('Kultur', 'die', 'kültür', 'culture'),
  n('Natur', 'die', 'doğa', 'nature'),
  n('Umwelt', 'die', 'çevre', 'environment'),
];
