// Extended German adverbs, connectors and everyday phrases — batch 5.
// Hand-checked Turkish meanings.
import type { CuratedWord } from '@/lib/mock-data';

const w = (
  word: string,
  type: 'adverb' | 'phrase',
  tr: string,
  en: string,
): CuratedWord => ({ id: word, word, language: 'de', type, shortDef: { tr, en } });

const adv = (word: string, tr: string, en: string) => w(word, 'adverb', tr, en);
const phr = (word: string, tr: string, en: string) => w(word, 'phrase', tr, en);

export const GERMAN_ADVERBS_EXTRA: CuratedWord[] = [
  // ── Time ────────────────────────────────────────────────────────────────────
  adv('früher', 'eskiden, daha önce', 'earlier, in the past'),
  adv('später', 'sonra, daha sonra', 'later'),
  adv('damals', 'o zamanlar', 'back then'),
  adv('neulich', 'geçenlerde', 'recently'),
  adv('vorhin', 'az önce', 'a moment ago'),
  adv('gerade', 'tam şu an, henüz', 'just now'),
  adv('zuerst', 'önce, ilk olarak', 'first'),
  adv('danach', 'ondan sonra', 'afterwards'),
  adv('zuletzt', 'en son', 'lastly'),
  adv('schließlich', 'sonunda, nihayet', 'finally'),
  adv('inzwischen', 'bu arada, o sırada', 'in the meantime'),
  adv('normalerweise', 'normalde, genellikle', 'normally'),
  adv('meistens', 'çoğunlukla', 'mostly'),
  adv('ständig', 'sürekli', 'constantly'),
  adv('täglich', 'günlük, her gün', 'daily'),
  adv('bisher', 'şimdiye kadar', 'so far'),
  adv('rechtzeitig', 'zamanında', 'in time'),
  adv('plötzlich', 'aniden', 'suddenly'),

  // ── Place & direction ───────────────────────────────────────────────────────
  adv('oben', 'yukarıda', 'above, up'),
  adv('unten', 'aşağıda', 'below, down'),
  adv('vorne', 'önde', 'in front'),
  adv('hinten', 'arkada', 'at the back'),
  adv('mitten', 'ortada', 'in the middle'),
  adv('nirgendwo', 'hiçbir yerde', 'nowhere'),
  adv('irgendwo', 'bir yerde', 'somewhere'),
  adv('weg', 'uzakta, gitmiş', 'away'),
  adv('herum', 'etrafta, çevrede', 'around'),

  // ── Degree & manner ─────────────────────────────────────────────────────────
  adv('besonders', 'özellikle', 'especially'),
  adv('wirklich', 'gerçekten', 'really'),
  adv('eigentlich', 'aslında, esasen', 'actually'),
  adv('kaum', 'neredeyse hiç, zar zor', 'hardly'),
  adv('völlig', 'tamamen', 'completely'),
  adv('teilweise', 'kısmen', 'partly'),
  adv('ungefähr', 'yaklaşık', 'approximately'),
  adv('mindestens', 'en az', 'at least'),
  adv('höchstens', 'en fazla', 'at most'),
  adv('sogar', 'hatta, bile', 'even'),
  adv('zumindest', 'hiç değilse, en azından', 'at least'),
  adv('lieber', 'tercihen, daha iyi', 'rather, preferably'),
  adv('genauso', 'tıpkı, aynı şekilde', 'just as'),
  adv('umsonst', 'boşuna; bedava', 'in vain; free'),
  adv('absichtlich', 'kasten, bilerek', 'on purpose'),

  // ── Connectors ──────────────────────────────────────────────────────────────
  adv('deshalb', 'bu yüzden', 'therefore'),
  adv('trotzdem', 'yine de, buna rağmen', 'nevertheless'),
  adv('außerdem', 'ayrıca, üstelik', 'besides'),
  adv('jedoch', 'ancak, fakat', 'however'),
  adv('dennoch', 'yine de', 'still, yet'),
  adv('also', 'yani, öyleyse', 'so, thus'),
  adv('zum Beispiel', 'örneğin', 'for example'),
  adv('einerseits', 'bir yandan', 'on the one hand'),
  adv('andererseits', 'diğer yandan', 'on the other hand'),
  adv('beziehungsweise', 'ya da, daha doğrusu', 'or rather'),
  adv('nämlich', 'şöyle ki, çünkü', 'namely'),
  adv('letztlich', 'nihayetinde, sonuçta', 'ultimately'),
  adv('immerhin', 'her şeye rağmen, hiç değilse', 'at least, after all'),
  adv('sowieso', 'zaten, nasılsa', 'anyway'),
  adv('übrigens', 'bu arada, sahi', 'by the way'),
  adv('hingegen', 'buna karşılık', 'on the contrary'),
  adv('folglich', 'dolayısıyla', 'consequently'),
  adv('demnach', 'buna göre', 'accordingly'),
  adv('gegebenenfalls', 'gerekirse, icabında', 'if necessary'),
  adv('keinesfalls', 'asla, hiçbir şekilde', 'by no means'),
  adv('zweifellos', 'kuşkusuz', 'undoubtedly'),
  adv('offensichtlich', 'belli ki, açıkça', 'evidently'),
  adv('vermutlich', 'muhtemelen', 'presumably'),
  adv('hauptsächlich', 'başlıca, çoğunlukla', 'mainly'),
  adv('insgesamt', 'toplamda, genel olarak', 'in total'),
  adv('vorwiegend', 'ağırlıklı olarak', 'predominantly'),
  adv('ebenfalls', 'aynı şekilde, keza', 'likewise'),
  adv('ebenso', 'aynen, tıpkı', 'equally'),
  adv('keineswegs', 'kesinlikle değil', 'not at all'),
  adv('durchaus', 'kesinlikle, tamamen', 'thoroughly, certainly'),
  adv('einigermaßen', 'şöyle böyle, bir ölçüde', 'somewhat'),
  adv('möglichst', 'olabildiğince', 'as much as possible'),
  adv('teils', 'kısmen', 'partly'),
  adv('vorerst', 'şimdilik', 'for now'),
  adv('seitdem', 'o zamandan beri', 'since then'),
  adv('bislang', 'şimdiye dek', 'so far'),
  adv('demnächst', 'yakında, ileride', 'shortly'),
  adv('jederzeit', 'her an, istediğin zaman', 'at any time'),
  adv('irgendwann', 'bir ara, bir gün', 'sometime'),
  adv('mehrmals', 'birkaç kez', 'several times'),
  adv('erneut', 'yeniden', 'again, anew'),
  adv('vergeblich', 'boşuna', 'in vain'),
];

export const GERMAN_PHRASES_EXTRA: CuratedWord[] = [
  phr('guten Tag', 'iyi günler', 'good day, hello'),
  phr('auf Wiedersehen', 'hoşça kal, görüşmek üzere', 'goodbye'),
  phr('bis morgen', 'yarın görüşürüz', 'see you tomorrow'),
  phr('schönen Tag noch', 'iyi günler dilerim', 'have a nice day'),
  phr('gute Reise', 'iyi yolculuklar', 'have a good trip'),
  phr('gute Besserung', 'geçmiş olsun', 'get well soon'),
  phr('viel Spaß', 'iyi eğlenceler', 'have fun'),
  phr('guten Appetit', 'afiyet olsun', 'enjoy your meal'),
  phr('vielen Dank', 'çok teşekkürler', 'thank you very much'),
  phr('gern geschehen', 'rica ederim', 'you are welcome'),
  phr('Verzeihung', 'affedersiniz', 'pardon'),
  phr('macht nichts', 'önemli değil', 'never mind'),
  phr('einverstanden', 'kabul, anlaştık', 'agreed'),
  phr('stimmt', 'doğru, haklısın', 'that is right'),
  phr('natürlich gern', 'tabii, memnuniyetle', 'of course, gladly'),
  phr('ich weiß nicht', 'bilmiyorum', 'I do not know'),
  phr('das macht Sinn', 'bu mantıklı', 'that makes sense'),
  phr('ich bin müde', 'yorgunum', 'I am tired'),
  phr('ich habe Hunger', 'acıktım', 'I am hungry'),
  phr('ich habe Durst', 'susadım', 'I am thirsty'),
  phr('wie spät ist es', 'saat kaç', 'what time is it'),
  phr('wo wohnst du', 'nerede oturuyorsun', 'where do you live'),
  phr('was ist los', 'ne oldu, sorun ne', 'what is wrong'),
  phr('das gefällt mir', 'bu hoşuma gitti', 'I like that'),
  phr('viel Erfolg', 'başarılar', 'good luck, all the best'),
  phr('bis dann', 'o zamana kadar görüşürüz', 'see you then'),
  phr('eine Frage bitte', 'bir soru sorabilir miyim', 'a question, please'),
  phr('langsam bitte', 'lütfen yavaş', 'slowly, please'),
  phr('noch einmal bitte', 'bir daha lütfen', 'once more, please'),
];
